### ISSUE TITLE
Debugger can't terminate on program end

### ISSUE THREAD

**Issue by roblourens** [Microsoft/vscode-node-debug2#11]
Currently, when the script terminates and a debugger is attached, Node waits for the debugger to detach before quittting, but the debugger has no way to know. I think a result of https://github.com/nodejs/node/issues/7088

Already tracked in - Nodejs/Node#7742

**Comment by roblourens** [comment]
Node in some versions has a similar issue, so this probably isn't high priority.

**Comment by roblourens** [comment]
I could listen on stderr for "Waiting for the debugger to disconnect..." but not a good solution

**Comment by mousetraps** [comment]
Interestingly, after hitting this issue, I pressed `step over` a gazillion times, and the process actually exited at the end.

**Comment by rianadon** [comment]
Now that https://github.com/nodejs/node/issues/7742 has been resolved, what needs to be done to fix this?

I'd be happy to provide a PR but given that the bulk of functionality comes from [vscode-chrome-debug-core](https://github.com/Microsoft/vscode-chrome-debug-core), I'm not sure where to fix this.

**Comment by roblourens** [comment]
Thanks for pointing that out, I should have subscribed to the issue. A PR would be awesome, it should be fairly simple. The fix will be in this repo, at least for now.

Override `protected hookConnectionEvents(): void {` from -core's `ChromeDebugAdapter`. Add a listener for the `Runtime.executionContextDestroyed` event. Check that the id=1 (I don't know what else in node would cause a context to be created and destroyed? And call `terminateSession` when that happens.

**Comment by rianadon** [comment]
Thanks for all those instructions! If you haven't already seen it the PR is #112.
