### ISSUE TITLE
Debugger does not stop after code execution finishes

### ISSUE THREAD

**Issue by rianadon** [Microsoft/vscode-node-debug2#111]
First of all, I'm not sure if this issue should be filed under this repo or under [vscode-node-debug](https://github.com/Microsoft/vscode-node-debug) as the `type` key in my `launch.json` is set to `node`, but I'm using the inspector protocol.

That said, when debugging a very simple Node.js program (like one containing only a `console.log`), the debugger will continue being active after the program finishes, while I would expect it to stop when there is nothing left to debug.

**Comment by roblourens** [comment]
This is the right repo, thanks. This is #11

**Comment by rianadon** [comment]
Oh oops didn't see that issue. Thanks 😄
