### ISSUE TITLE
Add the ability to control if the nodejs console window closes on exit of the node app.

### ISSUE THREAD

**Issue by paulvanbrenk** [Microsoft/vscode-node-debug2#113]
Add the ability to control if the nodejs console window closes on exit of the node app.

Based on the exit code, we would like the following options.

* `both` always keeps the console open
* `normal` keeps the console open when the exit code is `0`
* `abnormal` keeps the console open when the exit code is not `0`
* `default` close the console, when the app exits

**Comment by weinand** [comment]
@roblourens are using the DAP 'runInTerminal' request for running node.js in the console? If yes, then this feature request can probably be moved to VS Code.

**Comment by roblourens** [comment]
This issue was moved to Microsoft/vscode#30525

**Comment by roblourens** [comment]
Good point, done
