### ISSUE TITLE
Sourcemap "sections" doesn't seem to be supported

### ISSUE THREAD

**Issue by Alphapage** [Microsoft/vscode-node-debug2#117]
Hello,

If I add sections to the sourcemap, then I get the error : 'Cannot read property map of undefined'.
Is it a bug or do you plan to add such a feature ?

Thank you in advance for your answers.

**Comment by roblourens** [comment]
What do you mean by "sections"?

**Comment by Alphapage** [comment]
From the specs, you can include offset with map in the sections field:
https://docs.google.com/document/d/1U1RGAehQwRypUTovF1KRlpiOFze0b-_2gc6fAH0KY0k/edit#heading=h.535es3xeprgt

**Comment by roblourens** [comment]
Not supported - I'm guessing the error is from missing another expected part of the sourcemap. Will track in -core.
