### ISSUE TITLE
Consider to support new response format for 'getLoadedScripts'

### ISSUE THREAD

**Issue by weinand** [Microsoft/vscode-node-debug2#119]
The node-debug extension now supports a less redundant format for the 'getLoadedScripts' response: it is just an array of paths. And the sorting is now done in the UI. This reduced the implementation in node-debug to this:

```js
	private allLoadedScriptsRequest(response: DebugProtocol.Response, args: any) {
		this._node.scripts( { types: 4 } ).then(resp => {
			const paths = resp.body.map(script => this._scriptToPath(script));
			response.body = { paths: paths };
			this.sendResponse(response);
		}).catch(err => {
			this.sendErrorResponse(response, 9999, `scripts error: ${err}`);
		});
	}
```

Please let me know when node-debug2 sends the new format and I will remove the compatibility code in the node-debug extension.

**Comment by roblourens** [comment]
Implemented in https://github.com/Microsoft/vscode-chrome-debug-core/commit/886d3af7fe1b9f21f9720fa828df08c13de12a6c
