### ISSUE TITLE
Support "remoteRoot" and "localRoot" for "launch" request type

### ISSUE THREAD

**Issue by weinand** [Microsoft/vscode-node-debug2#120]
This is already supported for the "legacy" protocol.

**Comment by weinand** [comment]
@roblourens Since I see some requests for a multi-path version of "remoteRoot"/"localRoot" I wonder
whether we should consider to consolidate the more flexible "sourceMapPathOverrides" from node-debug2 or the "pathMapping" from Chrome Debug with "remoteRoot"/"localRoot".

So "remoteRoot"/"localRoot" would become just a shortcut for something more flexible?

What do you think?

**Comment by auchenberg** [comment]
Already looks to be supported, https://github.com/Microsoft/vscode-node-debug2/blob/master/package.json#L284?

Implemented in vscode-chrome-debug-core: https://github.com/Microsoft/vscode-chrome-debug-core/search?utf8=%E2%9C%93&q=remoteRoot&type=

**Comment by weinand** [comment]
@auchenberg "remoteRoot" and "localRoot" is only available for the "attach" request, but not for "launch". Please see the enclosing "attach" object: https://github.com/Microsoft/vscode-node-debug2/blob/master/package.json#L235

In node-debug we had "remoteRoot" and "localRoot" initially only for "attach" and added them to the "launch" request two month ago.

**Comment by roblourens** [comment]
I think remoteRoot/localRoot are analogous to pathMapping. I think we should keep a separation between sourceMapPathOverrides, and something like pathMapping. But I'm all for supporting something like pathMapping for node-debug2 if people need it.

**Comment by weinand** [comment]
Ok, will look into using "pathMapping" as the new official mechanism and "remoteRoot/localRoot" for backward compatibility. 'll prototype this on node-debug first.
