### ISSUE TITLE
Do not use "--debug-brk" if a runtimeExecutable is specified

### ISSUE THREAD

**Issue by weinand** [Microsoft/vscode-node-debug2#121]
Currently node-debug2 passes a combination of "--inspect" and "--debug-brk" flags when launching node.js (and any other "runtimeExecutable"). This is done because node.js versions < v8.0 do not support "--inspect-brk" but instead the combination only).

Since I'm not sure that Electron (or other runtimeExecutables) will support this combination too, I suggest that we stop using the combination whenever a runtimeExecutable is specified.  

Does this make sense?

See https://github.com/Microsoft/vscode/issues/30504#issuecomment-315189844

**Comment by roblourens** [comment]
I just put Microsoft/vscode#27731 on the July milestone, I'll track it there.
