### ISSUE TITLE
Breakpoints in some eval code need offsets

### ISSUE THREAD

**Issue by Alphapage** [microsoft/vscode-node-debug2#122]
Hello,

I created a repo to show the error:
https://github.com/Alphapage/sourcemapsexample

When trying to debug my babel code with vscode, I wasn't able to get the correct line for `debugger;`.
I didn't know if it was babel, my code or node debug2, so I created a repo to compare and the problem comes from vscode.
I added some quick instructions to compare both.

Is it a nodejs version problem or node-debug2 offset engine problem ?
How do you debug node-debug2 and sourcemapsexample at the same time ? Can't find any info and wasn't able to find a hack by myself ,sorry ?

Thank you in advance for your help.

**Comment by roblourens** [comment]
https://github.com/Microsoft/vscode-chrome-debug-core/pull/221
