### ISSUE TITLE
Adapter shows deprecated warning when debugging node 8

### ISSUE THREAD

**Issue by mbraude** [Microsoft/vscode-node-debug2#123]
Debugging Node.js 8 shows this warning:

Debugger listening on ws://127.0.0.1:13801/4b1faf92-892e-421c-b7d0-36368ad78570 For help see https://nodejs.org/en/docs/inspector Debugger attached. (node:24316) 
[DEP0062] DeprecationWarning: `node --inspect --debug-brk` is deprecated. Please use `node --inspect-brk` instead.

**Comment by roblourens** [comment]
Will transition to `--inspect-brk`, tracked in https://github.com/Microsoft/vscode/issues/27731

**Comment by roblourens** [comment]
https://github.com/Microsoft/vscode/issues/27731 is fixed 🎉
