### ISSUE TITLE
Add node version to thread name

### ISSUE THREAD

**Issue by roblourens** [Microsoft/vscode-node-debug2#129]
See https://github.com/Microsoft/vscode-node-debug/commit/23dd8c81

**Comment by auchenberg** [comment]
/What's the scenario where Node version is needed?

**Comment by roblourens** [comment]
I would find it useful since I spend a lot of time switching versions with `nvm` and running `node -v`. These labels only show up when you are attached to multiple things however.

**Comment by auchenberg** [comment]
Gotcha, just sounds like a super user use-case and not something the average dev could care about.
