### ISSUE TITLE
Uncaught Exception when starting an extension debugging session

### ISSUE THREAD

**Issue by weinand** [Microsoft/vscode-node-debug2#132]
After switching EH debugging to "inspector" protocol,  we are running now into the same issue we had for "legacy": https://github.com/Microsoft/vscode/issues/24482:

![2017-08-14_10-38-49](https://user-images.githubusercontent.com/1898161/29264816-cfffd738-80de-11e7-94fc-bd9e0a5288f0.png)

I suggest to fix it in the same way I did for "legacy" (and since we both know that the 'reject' detection heuristic is a bit of a hack, this exception config option only shows up for debug type "extensionHost").

**Comment by roblourens** [comment]
It's not as easy, because the v8 protocol got the line of text when a break happens, right? But with the inspector protocol I need to request the full script text to find the line. Can we skip all the non-user files with `skipFiles`?

**Comment by roblourens** [comment]
I just realized, the debug adapter does in fact know when it's breaking on a promise rejection, that's how the message says "Paused on Promise Rejection". So I should add the exception filter, and continue when breaking on a promise rejection when that option isn't selected.

You could even make an argument for enabling this all the time, not just for extensionHost debugging. The only question is, could it be confusing if "Uncaught Exceptions" is checked, and "Promise rejects" isn't checked, and the user is expecting it to break on some error which they don't realize is a rejected promise, not a typical exception.

**Comment by weinand** [comment]
1. Yes, we could use `skipFiles` for this.
But if this setting would be explicit in the default extension launch config, it would only become available for newly created launch configs.
Users with existing launch configs would suffer. To address this we could use an implicit hidden `skipFiles` setting if the user did not specify `skipFiles` at all.

2. yes, if you are able to show "Paused on Promise Rejection", then you could offer the  exception filter as well. That would be the best solution and would make the transition from "legacy" to "inspector" based EH debugging smooth.

3. IMO the confusion that you mention is smaller in comparison to the confusion of having user handled rejects behind the "Uncaught Exceptions" option.

4. If you think that we should offer the exception filter always, then lets do it!

**Comment by auchenberg** [comment]
Webpack had a similar issue, and we ended up changing the how the promise is rejected: https://github.com/webpack/webpack/pull/5308

See discussion on the Chrome tracker, https://bugs.chromium.org/p/chromium/issues/detail?id=465666

**Comment by roblourens** [comment]
It works to continue when node reports that we paused on a rejected promise, but there is at least one case where it incorrectly doesn't report that it's paused on an exception: https://bugs.chromium.org/p/chromium/issues/detail?id=755728

This `Promise.reject` case is working correcting in the actual problematic extensionHost code, apparently because it shows up in another promise chain and that makes things work out differently. But I have no idea whether that will always be the case so I don't want to trust it.
