### ISSUE TITLE
Launch doesn't work with PowerShell as default shell in integratedTerminal

### ISSUE THREAD

**Issue by auchenberg** [Microsoft/vscode-node-debug2#133]
_From @riker09 on August 9, 2017 7:31_

I'm trying to get remote debugging in a docker container to work. I have a strong linux background but at work I'm stuck with Windows (unfortunately). I think this error has to do something with Windows, but I'm not 100% sure:

```
PS C:\Users\MYUSER\projects\vscode-recipes\Docker-TypeScript> cd 'c:\Users\MYUSER\projects\vscode-recipes\Docker-TypeScript'; 'C:\Program Files\nodejs\npm.cmd' run docker-debug
In Zeile:1 Zeichen:99
+ ... pes\Docker-TypeScript'; 'C:\Program Files\nodejs\npm.cmd' run docker- ...
+                                                               ~~~
Unerwartetes Token "run" in Ausdruck oder Anweisung.
    + CategoryInfo          : ParserError: (:) [], ParentContainsErrorRecordException
    + FullyQualifiedErrorId : UnexpectedToken

PS C:\Users\MYUSER\projects\vscode-recipes\Docker-TypeScript>
```

_Copied from original issue: weinand/vscode-recipes#17_

**Comment by auchenberg** [comment]
@riker09 Can you try to post your "launch.json" file in here? Looks like `npm.cmd` is being called in a wrong way.

**Comment by auchenberg** [comment]
_From @riker09 on August 10, 2017 7:29_

Sure, no problem:

```json
{
  "version": "0.2.0",
  "configurations": [
    {
      "type": "node",
      "request": "launch",
      "name": "Launch in Docker",
      "protocol": "legacy",
      "runtimeExecutable": "npm",
      "runtimeArgs": [ "run", "docker-debug" ],
      "port": 5858,
      "restart": true,
      "timeout": 60000,
      "localRoot": "${workspaceRoot}",
      "remoteRoot": "/app",
      "outFiles": [
        "${workspaceRoot}/**/*.js"
      ],
      "console": "integratedTerminal",
      "internalConsoleOptions": "neverOpen"
    }
  ]
}
```

As a workaround I switched `console` to `externalTerminal`, that seem to work just fine, albeit an extra window is somwhat annoying. 😐

**Comment by auchenberg** [comment]
@riker09 What version of Code are you using?

**Comment by auchenberg** [comment]
_From @roblourens on August 10, 2017 18:51_

```
PS C:\Users\roblou\code\jstest> 'C:\Program Files\nodejs\npm.cmd' run build
At line:1 char:35
+ 'C:\Program Files\nodejs\npm.cmd' run build
+                                   ~~~
Unexpected token 'run' in expression or statement.
    + CategoryInfo          : ParserError: (:) [], ParentContainsErrorRecordException
    + FullyQualifiedErrorId : UnexpectedToken
```

I guess that isn't valid PS syntax... I actually am not sure what it should be...?

**Comment by auchenberg** [comment]
_From @roblourens on August 10, 2017 18:52_

Oh, it should be `& 'C:\Program Files\nodejs\npm.cmd' run build`, otherwise the `program files/...` arg is just a string.

I guess we need to do this differently when the shell is powershell, because that won't work in cmd.

**Comment by auchenberg** [comment]
_From @riker09 on August 11, 2017 8:51_

@auchenberg I was using VS Code 1.14.

**Comment by auchenberg** [comment]
@riker09 Gotcha. And you are using PowerShell as your default shell? Seems like you have hit a scenario that we don't support today for the `integratedTerminal`, as we are running the launch script for non-PS.

**Comment by auchenberg** [comment]
_From @riker09 on August 15, 2017 7:40_

I haven't touched the defaults made by Windows, so I guess my default shell is powershell. I would confirm it, but I don't know where to start looking.

**Comment by roblourens** [comment]
We can check `"terminal.integrated.shell.windows": "cmd.exe"` and construct a different string when in powershell.

**Comment by weinand** [comment]
Please note: access to settings is not possible in DAs since they should work in non VS Code-contexts as well.

**Comment by roblourens** [comment]
If it's safe for vscode to do this without knowing what the command "means", then that would be preferable. I figured the extensionhost could also pass this info along to the debug adapter.

**Comment by weinand** [comment]
Yes, if we cannot fix this in VS Code, we can do it in the EH and pass it as part of the launch config to the DA.

**Comment by roblourens** [comment]
I believe this has been fixed to write the correct syntax for commands with ' ' in PS.
