### ISSUE TITLE
column breakpoint jumps ahead

### ISSUE THREAD

**Issue by Spown** [Microsoft/vscode-node-debug2#143]
When setting a column breakpoint it jumps ahead onto a random line
![](https://drive.google.com/uc?id=0B-OJBofmehO3aHA4eTQ4WHQwZTQ)
and when running the column point vanishes and it converts into a normal breakpoint, still on the wrong line
![](https://drive.google.com/uc?id=0B-OJBofmehO3RW0yVk0yNjRnOFk)

**Comment by Spown** [comment]
I think disappearing column point indicator is a separate problem though. Probably VSC's problem, not the debuggers. Since for example [vscode-firefox-debug](/hbenl/vscode-firefox-debug) seems to work fine, but when running the indicator vanishes also.

**Comment by roblourens** [comment]
Depends on the code, or sourcemaps if applicable. Can you post the full code snippet?

**Comment by Spown** [comment]
nope, just plain 'ol js. 

```js
var a = function(inVal) {return {then: function (cb) {cb(inVal)}}}
if (1) {
    console.log('1');
    a(2)
    .then(function (c) { /* here-> */console.log(c) });
} else {
    console.log('not')
}
```

Setting the breakpoint via hotkey then running -> jumps after reaching the line:
![](https://drive.google.com/uc?id=0B-OJBofmehO3WnFnZnFxU2JDRGc)

Setting the breakpoint via hotkey while running -> jumps immediately after couple ms delay:
![](https://drive.google.com/uc?id=0B-OJBofmehO3T3NhSi1DakNkTjQ)

**Comment by roblourens** [comment]
What version of node? Column BPs don't work before Node 8. Same behavior in Chrome devtools. With 8.0.0:

![image](https://user-images.githubusercontent.com/323878/30785296-cb16488c-a119-11e7-9692-a126baf1451f.png)

**Comment by Spown** [comment]
Right now 7 but I moved from 6 just yesterday and I remember seeing this behavior prior.

**Comment by roblourens** [comment]
Node 6 didn't support column breakpoints. I just tried it again in CDT to confirm.

**Comment by Spown** [comment]
Wouldn't harm to turn them off (hide/grayout from context menu and debugging menu) to not confuse people if Node < 8. Also hint [here](https://code.visualstudio.com/docs/editor/debugging#_breakpoints) maybe?

Thanks.

**Comment by roblourens** [comment]
Hm, we don't have a way to dynamically disable debugger features right now. Hopefully it will be less of a problem as more people move onto Node 8. cc @weinand 

That section in the docs is about breakpoints in general, not for node specifically (although all the examples are debugging node). Maybe it would make sense to have a sentence about it in https://code.visualstudio.com/docs/nodejs/nodejs-debugging#_breakpoint-validation?

**Comment by Spown** [comment]
something would definitely be better than nothing. I mean before this issue here there were no way to tell why it didn't work.
