### ISSUE TITLE
Adjust columns on positions at line=0 to account for node module wrapper

### ISSUE THREAD

**Issue by roblourens** [microsoft/vscode-node-debug2#145]
Easy to see one example:

```
console.log('a');
console.log('b');
```

Click the location in the debug console for each of these. See that the first one goes to the end of the line, and the second goes to `log`. The first actually returns column 70 because it doesn't account for the ~60 characters of the node module wrapper on line 0.

In general I don't account for this and positions in column breakpoints or elsewhere on line 0 could be messed up.

**Comment by connor4312** [comment]
No longer needed as of Node 8
