### ISSUE TITLE
VSCode randomly starts throwing Exception "TypeError: Cannot convert object to primitive value" at startup while debugging

### ISSUE THREAD

**Issue by honestserpent** [Microsoft/vscode-node-debug2#148]
**Steps to Reproduce:**

There is literally no way I can't report the steps to reproduce this, because I literally didn't do anything.

1. Everything was working fine.
2. Suddenly, running F5 to debug, VSCode started to throw this Exception at startup:

`TypeError: Cannot convert object to primitive value
  at c:\Users\myusername\workspace\checkinwebbackend\node_modules\lodash-compat\internal\isHostObject.js:10:30
  at Object.<anonymous> (c:\Users\myusername\workspace\checkinwebbackend\node_modules\lodash-compat\internal\isHostObject.js:19:2)
  at Module._compile (module.js:569:30)
  at Object.Module._extensions..js (module.js:580:10)
  at Module.load (module.js:503:32)
  at tryModuleLoad (module.js:466:12)
  at Function.Module._load (module.js:458:3)
  at Module.require (module.js:513:17)
  at require (internal/module.js:11:18)
  at Object.<anonymous> (c:\Users\myusername\workspace\checkinwebbackend\node_modules\lodash-compat\lang\isNative.js:2:20)`

3. If I run the app from the command line without debugging, everything works fine.

I cannot do anything more because the application crashes at startup.
This problem happens with both VSCode 1.17.1 and Insider edition (1.18.0)

My .vscode/launch.json file:

`{
    // Use IntelliSense to learn about possible Node.js debug attributes.
    // Hover to view descriptions of existing attributes.
    // For more information, visit: https://go.microsoft.com/fwlink/?linkid=830387
    "version": "0.2.0",
    "configurations": [
        {
            "type": "node",
            "request": "launch",
            "name": "Launch app.js",
            "program": "${workspaceRoot}\\server\\app.js"
        }
    ]
}`

- VSCode Version: 1.17.1
- OS Version: Windows 10 Pro 64bit

**Comment by roblourens** [comment]
Looks like an error from your app, possibly a node bug if it only happens in debug mode. What happens at that line?

**Comment by honestserpent** [comment]
We do not know.

We are using loopback and the exception is thrown at the very first line of the main script:

`var loopback = require('loopback')`

Apparently it only happens in debug mode. I also run the script using 'node --inspect-brk app.js' and the app works correctly.

If you think this is not a VSCode but, where could I post?

**Comment by roblourens** [comment]
Try it with the latest node version, and if it still reproes, you could file an issue on the node repo, https://github.com/nodejs/node/issues.

**Comment by honestserpent** [comment]
ok, thank you
