### ISSUE TITLE
Can't put running Node process into debug mode

### ISSUE THREAD

**Issue by roblourens** [Microsoft/vscode-node-debug2#15]
https://github.com/nodejs/node/issues/8464

**Comment by auchenberg** [comment]
This is now scheduled to landing in Node 8.x.x

https://github.com/nodejs/diagnostics/pull/76

**Comment by jkrems** [comment]
This is the exact change in node itself required for this feature: https://github.com/nodejs/node/pull/11431

**Comment by auchenberg** [comment]
Landed in Node. No longer blocked.

**Comment by auchenberg** [comment]
Validated over the weekend with Node nightly. Prototyped in: https://github.com/auchenberg/debug-tunnel/blob/master/index.js#L34

**Comment by roblourens** [comment]
Discussion about this in https://github.com/Microsoft/vscode/issues/25036 - not sure I'll get to it in May, though.

**Comment by roblourens** [comment]
Using https://github.com/Microsoft/vscode/issues/25036 for this
