### ISSUE TITLE
Source maps don't work correctly with babel-node and WSL

### ISSUE THREAD

**Issue by noinkling** [microsoft/vscode-node-debug2#151]
Basically I can't set breakpoints in the original files ...well I kinda can but they behave strangely/move/aren't hit when expected, as if the debugger is looking at the Babel-compiled version of the file.

If I add a `debugger` statement it will pause but a *new* editor will open with a "read-only inlined content from source map" version of the file. I can use this editor to set breakpoints and they will work as expected. When mousing over the tab it gives a path like `c:\mnt\c\...`, so it seems like the path isn't being mapped correctly at some point (see `.scripts` output below). Also the little file link that appears next to any logging output will open this version. If I mouseover this link it will show a string/URI like `debug:<uri encoded version of the aforementioned path>?session<some other uri encoded stuff>`

Versions:

- VS Code 1.18.0 (x64)
- Node 9.1.0 (in WSL)
- babel-cli 6.26.0

Config:

```json
{
  "type": "node",
  "request": "launch",
  "name": "Launch Server (WSL)",
  "useWSL": true,
  "program": "${workspaceFolder}/src/server/index.js",
  "runtimeExecutable": "./node_modules/.bin/babel-node",
  "sourceMaps": true
}
```

Debug console:

```
Debugging with inspector protocol because a runtime executable is set.
C:\WINDOWS\System32\bash.exe -ic './node_modules/.bin/babel-node --inspect=10314 --debug-brk src/server/index.js' 
Debugger listening on ws://127.0.0.1:10314/8e06abba-774e-4d89-b165-16c942fc1ab0
Debugger attached.
...
```

A couple of relevant lines from the `.scripts` command:

```
› /mnt/c/Dev/Projects/my-project/src/server/index.js (c:\Dev\Projects\my-project\src\server\index.js)
    - \mnt\c\Dev\Projects\my-project\src\server\index.js (c:\mnt\c\Dev\Projects\my-project\src\server\index.js)
```

If I browse to `index.js` under "Loaded scripts" in the sidebar and open it, I see the Babel-compiled version of the file. If I mouse over the tab it tells me the path is `/mnt/c/Dev/Projects/my-project/src/server/index.js` (not sure if this is relevant, but AFAIK this compiled version actually only exists in memory). At the bottom I can see the inline source map that was produced:

```js
//# sourceMappingURL=data:application/json;charset=utf-8;base64,<bunch of base64 encoded stuff>
```

Here are a couple of potentially relevant bits of the decoded json, in case it's helpful:

```
{"version":3,"sources":["index.js"],
...
"file":"index.js","sourceRoot":"/mnt/c/Dev/Projects/my-project/src/server",
...
}
```

I should probably mention that babel-node seems to output inline source maps no matter what `sourceMaps` is set to in the .babelrc config.

**Comment by connor4312** [comment]
This should work better in our [new debugger](https://github.com/microsoft/vscode-js-debug/). Please open an issue there if not.
