### ISSUE TITLE
Double click on a file entry in **LOADED SCRIPTS** does not pin a document in the text editor.

### ISSUE THREAD

**Issue by changsi-an** [Microsoft/vscode-node-debug2#155]
After a node debug session is launched. I cannot pin a script file in the text editor by double-clicking it. While I can do so for the files in the Explorer viewlet. 

A work around to pin a document is to double-click its tab in the text editor after it's opened. (At the same time the font changes from italic to normal).

**Comment by roblourens** [comment]
This issue was moved to Microsoft/vscode#39601
