### ISSUE TITLE
Support file URLs for --experimental-modules

### ISSUE THREAD

**Issue by roblourens** [Microsoft/vscode-node-debug2#157]
When running Node with the `--experimental-modules` flag, it returns file paths as file URLs, not paths. We need to handle both formats.

We can set breakpoints without the file: prefix, because the regex still matches the rest. On Windows, slashes would have to changed to forward slashes.

**Comment by jpike88** [comment]
@roblourens just confirming that you think https://github.com/Microsoft/vscode/issues/45750 is directly related to this issue?

**Comment by roblourens** [comment]
Yes I am pretty sure it is

**Comment by zaverden** [comment]
@roblourens 
could you please share plans when it will be implemented?

As I can see, breakpoints work in CJS file even with `--experimental-modules` flag. I believe, URL-formated paths is only for ESM files, and it'll be this way after they came out of flag. 
In this case I believe a due date for file ULRs support is a date of a ESM release, but do you have plans to implement it earlier?

**Comment by roblourens** [comment]
No immediate plans but do you know when they will be out from the flag or considered "stable"?

**Comment by userpixel** [comment]
This works on Node 10 (I used [nvm](https://github.com/creationix/nvm)):

Open VS Code terminal and make sure you have Node 10:

```
$ nvm i 10

$ node --version
v10.4.0
```

### .vscode/launch.json
```
{
    // Use IntelliSense to learn about possible attributes.
    // Hover to view descriptions of existing attributes.
    // For more information, visit: https://go.microsoft.com/fwlink/?linkid=830387
    "version": "0.2.0",
    "configurations": [
        {
            "type": "node",
            "request": "launch",
            "name": "Launch Program",
            "program": "${workspaceFolder}/index.mjs",
            "runtimeArgs": [
                "--experimental-modules"
            ]
        }
    ]
}
```
