### ISSUE TITLE
ghost breakpoints after restart

### ISSUE THREAD

**Issue by Spown** [Microsoft/vscode-node-debug2#160]
When restarting debug session (via restart, not stop->start) after changing the code and a breakpoint was removed, debugger still breaks on the line where the bp was. 

Steps:
1. set a bp
2. initiate break
3. edit code
4. remove the bp
5. restart the debugger via restart command
6. initiate an action that would pass through where the bp was

![](https://drive.google.com/uc?id=16a7Z6JmP1I1vTtFqKoiXfuxFRPXcxypo)
![](https://drive.google.com/uc?id=1R44DFpkzDCGQ6lXEXCD06qX1vIKgOcTV)

Thank you.

**Comment by roblourens** [comment]
Sorry, I missed this one. I can't repro. Can you set `"trace": true`, run again, and upload the log here?

**Comment by Spown** [comment]
haven't seen in a while. so I'm closing it for now...
