### ISSUE TITLE
Debugger is not working in VS code

### ISSUE THREAD

**Issue by auchenberg** [Microsoft/vscode-node-debug2#161]
_From @vishalpwankhede on January 4, 2018 11:19_

Hi,
I am not able to debug in VS code for my project(was working before).

Throwing error: (node:24328) [DEP0062] DeprecationWarning: `node --debug` and `node --debug-brk` are invalid. Please use `node --inspect` or `node --inspect-brk` instead

VS Code details:
Version 1.19.1
Date 2017-12-19T09:41:01.414Z
Shell 1.7.9
Renderer 58.0.3029.110
Node 7.9.0
Architecture x64

Node version: v9.2.1

Thanks

_Copied from original issue: Microsoft/vscode-recipes#54_

**Comment by roblourens** [comment]
@vishalpwankhede could you post your launch config? What OS?

**Comment by vishalpwankhede** [comment]
@roblourens its
{
    "version": "0.2.0",
    "configurations": [{
            "type": "node",
            "request": "launch",
            "name": "Launch Program",
            "program": "${workspaceRoot}/bin/www",
            "restart": true,
            "protocol": "legacy"
        },
        {
            "type": "node",
            "request": "attach",
            "name": "Attach to Process",
            "port": 5858
        }
    ]
}

**Comment by roblourens** [comment]
`"protocol": "legacy"` You'll have to change that to "inspector", it won't work with "legacy" after Node 8

**Comment by vishalpwankhede** [comment]
Thanks @roblourens
