### ISSUE TITLE
Allow to run Node from node_modules/.bin

### ISSUE THREAD

**Issue by GingerPlusPlus** [Microsoft/vscode-node-debug2#168]
VSCode's Node debugger could add `./node_modules/.bin` to the beggining of PATH before running Node, which'd allow to use https://npmjs.com/node to easily use a version of Node different than the one installed on the system by running for example `npm i --no-save node@6`.

**Comment by weinand** [comment]
You can use the [new "runtimeVersion" attribute](https://code.visualstudio.com/updates/v1_20#_node-debugging) or something like:
```js
"runtimeExecutable": "${workspaceFolder}/node_modules/.bin/node"`
```

**Comment by GingerPlusPlus** [comment]
Thanks for your reply!

This is not what I asked for, but it'll do.

**Comment by GingerPlusPlus** [comment]
Still, I see possible improvements that could be made here:

1. `runtimeVersion` could be inferred from `packageJson.engines.node`,
2. If the right version is not installed (by system and via `nvm`), it could either install it locally and use that, or dispatch to `npx`. In case you didn't know, `npx node@6 main.js` launches `main.js` in Node 6.

If that was implemented, in most projects, you'd be one F5 away from launching the app in the right version of Node.

**Comment by weinand** [comment]
Please feel free to submit a PR.

**Comment by weinand** [comment]
This issue was moved to Microsoft/vscode#45126
