### ISSUE TITLE
Terminate DA when running without debugging from terminals

### ISSUE THREAD

**Issue by weinand** [Microsoft/vscode-node-debug2#169]
When running a program "without debugging" (Control + F5), the DA has no good way to get hold of the process ID of the program (and it will not be able to terminate the program when the red terminate button is pressed).

Consequently we should not keep up a debug session that serves no purpose.

I suggest that a DA sends a "terminate" event in this case (which makes VS Code stop the session silently).

The corresponding "legacy" bug is https://github.com/Microsoft/vscode-node-debug/issues/172

**Comment by roblourens** [comment]
But we still spawn the process so we get the pid from the child process handle right?

**Comment by roblourens** [comment]
"from terminals" got it
