### ISSUE TITLE
DAP: Adopt new "capabilities" event

### ISSUE THREAD

**Issue by weinand** [Microsoft/vscode-node-debug2#171]
We've introduced a new "capabilities" event (which ultimately will replace the unofficial way to update capabilities via a "launch" and "attach" response).

Please migrate to the new event for the "supportsStepBack" capability (see https://github.com/Microsoft/vscode-node-debug/commit/adaffb051fc83cee6694b59da5c1db2c62ffc237)

**Comment by weinand** [comment]
see https://github.com/Microsoft/vscode-node-debug/commit/adaffb051fc83cee6694b59da5c1db2c62ffc237

**Comment by roblourens** [comment]
Fixed in https://github.com/Microsoft/vscode-node-debug2/commit/20d8cb27ba1952c84632eb50bd311df34fcbd288
