### ISSUE TITLE
"chrome didn't shut down properly! Restore?"

### ISSUE THREAD

**Issue by Spown** [Microsoft/vscode-node-debug2#172]
I get this popup every time I stop debugging by either debugger stop or by closing VSCode altogether. Which happens alot . In fact I hardly ever close debugger session Chrome window itself.

And of course Chrome doesn't offer any way to turn it off. There is only a ["workaround" where you can freeze prefs file so that the browser thinks it has exited properly](https://productforums.google.com/forum/#!topic/chrome/ee6cqx5EBVA).

But in this case we (you) can do better. How about removing ``"exit_type":"Crashed"`` from and setting ``"exited_cleanly":true`` directly in the prefs file after the session or before starting a new one?

Thank you.

**Comment by roblourens** [comment]
Are you on windows? There's a PR in progress here: https://github.com/Microsoft/vscode-chrome-debug/pull/606

Also please file chrome-debug related issues in that repo.

**Comment by Spown** [comment]
whoops, wrong repo, sorry.
