### ISSUE TITLE
Use node --inspect-brk instead of --debug-brk for Node 10

### ISSUE THREAD

**Issue by digeff** [Microsoft/vscode-node-debug2#173]
Node 10 is deprecating --debug-brk.
We should use --inspect-brk instead of --debug-brk for Node 10

**Comment by roblourens** [comment]
It should be detecting support for that by running `node --version`. https://github.com/Microsoft/vscode-node-debug2/blob/32b87bd813735c14a2e25ad31c6acd0036673572/src/nodeDebugAdapter.ts#L186

Do you see it using `--inspect-brk`?

**Comment by roblourens** [comment]
Ping
