### ISSUE TITLE
runtimeVersion can cause the wrong debug args to be used

### ISSUE THREAD

**Issue by roblourens** [Microsoft/vscode-node-debug2#175]
- Have default node version of 8.0.0
- Set runtimeVersion to 7.0.0
- Start debugging - it will incorrectly use `--inspect-brk`

The `--inspect-brk` detection does not handle runtimeVersion

**Comment by Danieltsang** [comment]
https://github.com/Microsoft/vscode-node-debug2/commit/58072bbdad928177b79fb01e0f9d83afd437ea2b#diff-d03a74f75ec189cbc7dd3d2e105fc9c9R862 still uses the `--inspect-brk` option regardless of the node version. Can the logic for detecting the node version also be inserted there?

I use
```
{
      "name": "nodemon",
      "type": "node",
      "request": "launch",
      "runtimeExecutable": "nodemon",
      "runtimeArgs": [],
      "runtimeVersion": "6.9.0",
      "program": "${workspaceRoot}/server.js",
      "args": ["--watch", "api", "-e", "js,jsx"],
      "restart": true,
      "console": "integratedTerminal",
      "internalConsoleOptions": "neverOpen",
    },
``` on node 6.9.0, which does not support `--inspect-brk`.
