### ISSUE TITLE
yet another wild breakpoint jumping (backwards)

### ISSUE THREAD

**Issue by Spown** [Microsoft/vscode-node-debug2#176]
I kinda used to breakpoints in an empty function block jumping forward and outside (normally I put ``_.noop()`` or something else there to prevent it) but this one is new. It jumps backwards.
![](https://lh3.googleusercontent.com/-NAnvotpGO8Q/WqXMr5RCOYI/AAAAAAAAAqM/eBG0BQ4wnCI-WFaTqxDnyqNArmU_eaR7QCHMYCw/s0/2018-03-12_01-40-40.gif)

```js
gulp.task('i18n_for_browser', function() {
    var fakeSrc = stream.Readable({ objectMode: true }), //<- jumps here after session start
        nname = "i18n-for-browser.js"
    ;
    fakeSrc._read = function () {
        this.push(new gutil.File({
            cwd: "./node_modules",
            base: "i18n-for-browser-loader.js",
            path: "i18n-for-browser-loader.js",
            contents: new Buffer('i18n = require("i18n-for-browser");')
        }))
        this.push(null) //terminates file stream? hangs without
    }
    return // fakeSrc
        gulp.src("./i18n-for-browser-wrapper.js")
        //gulp.src("i18n-for-browser")
        .pipe(browfy())
        .pipe(rename(nname))
        .pipe(uglify({preserveComments:'license'}))
        .pipe(gulp.dest(defDestDir))
        .on("error", function(error) {
            gutil.log(gutil.colors(error.stack));
            this.emit("end");
        })
        .on('finish', function() {
            gutil.log(`built i18n-for-browser.js -> ${defDestDir+nname}`) //<-set here before the debugging
        })
    ;
});
```

Thank you

**Comment by Spown** [comment]
making sure that there is no comment between ``return`` and the further code makes this behavior go away.

```js
    return gulp.src("./i18n-for-browser-wrapper.js")
        //gulp.src("i18n-for-browser")
        // fakeSrc
```

**Comment by Spown** [comment]
@0.9.6 does compile ok.

**Comment by roblourens** [comment]
In the first case, your function actually returns undefined.

![image](https://user-images.githubusercontent.com/323878/37266594-6a2d9550-2578-11e8-8768-2199d1d30af9.png)

I think the code after `return` will be dead code.

**Comment by Spown** [comment]
hm, learn something new every day... thank you and sorry for the trouble.

**Comment by roblourens** [comment]
No worries. I had to try it. I would expect multiline return statements to work tbh.
