### ISSUE TITLE
Visual studio code doesn't debug node on windows

### ISSUE THREAD

**Issue by user135711** [Microsoft/vscode-node-debug2#182]
- VSCode Version: 1.21.1
- OS Version: Windows 10 and Windows server 2016

Steps to Reproduce:

1. Install the current [node ](https://nodejs.org/en/download/) (I tried versions 8-10)
2. Install vs code 1.21.1 on windows (I tried Server 2016 and Windows 10 and also VS insiders edition)
3. Create a new file and enter console.log("test"); press F5. 

### Expected output given by Ubuntu and documentation in debug console: 
node --inspect-brk=24959 test4.js 
Debugger listening on ws://127.0.0.1:24959/0b80b817-4d04-4613-aec6-5871ce1bbba6
Debugger attached.
Waiting for the debugger to disconnect...
test

### actual output: 
node --inspect-brk=24959 test4.js 
Debugger listening on ws://127.0.0.1:24959/0b80b817-4d04-4613-aec6-5871ce1bbba6

The program does not get run, and no breakpoints are hit. I followed the steps on 3 different VM's and only the unix installation works. 

Does this issue occur when all extensions are disabled?: Yes

**Comment by roblourens** [comment]
Works for me... so it prints out the output you gave, then nothing else happens? Does the debug widget appear? Do you set breakpoints in that file?

**Comment by user135711** [comment]
The debug widget does not appear. I tried setting breakpoints and they never get hit.

**Comment by roblourens** [comment]
Does an error message appear saying that it failed to attach, or anything else?

**Comment by user135711** [comment]
No error mesage, it just stops at that point. I know it's VS code because running node test.js outputs the "test" to console.

**Comment by roblourens** [comment]
That's weird because it should either show you an error message, or start debugging properly.

Can you try creating a launch config, set `"trace": true`, run it again, and upload the log here?

**Comment by user135711** [comment]
[debugadapter.txt](https://github.com/Microsoft/vscode-node-debug2/files/1832126/debugadapter.txt)

**Comment by roblourens** [comment]
> Websocket error: Error: write ECONNABORTED

Why would that happen...

One problem on my end is not surfacing the error message correctly.

Are you able to debug with chrome devtools? Start node in debug mode like `node --inspect-brk=24959 test4.js`, then go to `http://localhost:24959/json` in a browser, then navigate to the `devtoolsFrontendUrl` value.

**Comment by user135711** [comment]
Navigating to the [url](chrome-devtools://devtools/bundled/inspector.html?experiments=true&v8only=true&ws=127.0.0.1:24959/77f471db-711f-40a1-a3d3-7dd0d171e2bf) gives the error Debugging connection was closed. Reason: WebSocket disconnected. Reconnect when ready by reopening DevTools. Clicking Reconnect gives the same pop-up.

**Comment by user135711** [comment]
I got VS code working on a separate 4th VM running windows which is what I was wanting to use so I'm closing this. If I ever isolate what caused this problem I will re-open it for you to fix.

**Comment by user135711** [comment]
Update: If this error occurs for someone else, it is not VS Code. I got the same behavior with Visual Studio not attaching on the same VM's that VS Code didn't attach.
