### ISSUE TITLE
runtimeVersion can still cause the wrong debug args to be used

### ISSUE THREAD

**Issue by Danieltsang** [Microsoft/vscode-node-debug2#186]
As per https://github.com/Microsoft/vscode-node-debug2/issues/175, when using a `runtimeExecutable`, the node version is ignored and defaulted to `--inspect-brk`.

Here is the commit: https://github.com/Microsoft/vscode-node-debug2/commit/58072bbdad928177b79fb01e0f9d83afd437ea2b#diff-d03a74f75ec189cbc7dd3d2e105fc9c9R862

Can the logic for detecting the node version also be inserted there?

I use
```
{
      "name": "nodemon",
      "type": "node",
      "request": "launch",
      "runtimeExecutable": "nodemon",
      "runtimeArgs": [],
      "runtimeVersion": "6.9.0",
      "program": "${workspaceRoot}/server.js",
      "args": ["--watch", "api", "-e", "js,jsx"],
      "restart": true,
      "console": "integratedTerminal",
      "internalConsoleOptions": "neverOpen",
    },
```
on node 6.9.0, which does not support --inspect-brk.

This results in
```
[nodemon] starting `node --inspect-brk=24731 server.js`
node: bad option: --inspect-brk=24731
[nodemon] app crashed - waiting for file changes before starting...
```

**Comment by roblourens** [comment]
Good point, I didn't realize that runtimeExecutable is still relevant with runtimeVersion.

**Comment by amylu0712** [comment]
Appreciate the new change, thanks for catching that @Danieltsang!
