### ISSUE TITLE
Column positions are off by 1

### ISSUE THREAD

**Issue by roblourens** [Microsoft/vscode-node-debug2#19]

**Comment by jrieken** [comment]
![sep-27-2016 12-12-58](https://cloud.githubusercontent.com/assets/1794099/18869263/d64af26a-84ab-11e6-8103-fa4fe806da69.gif)

you mean that, right?

**Comment by roblourens** [comment]
Right

**Comment by roblourens** [comment]
https://github.com/Microsoft/vscode-chrome-debug-core/commit/dac9968177dfbf440c75c079b1db98a645f1cffc
