### ISSUE TITLE
Ability to use node engine greater than 6.3.0

### ISSUE THREAD

**Issue by tolusha** [Microsoft/vscode-node-debug2#190]
I would like use the project as a dependency but the only restriction is the node version.
It is possible to set node version engine greater then 6.3.0 ? Like on the snippet below.

```
  "engines": {
     ...
    "node":  >=6.3.0"
  },
```

**Comment by roblourens** [comment]
Sure but what do you want to use node-debug2 for? Are you trying to use it as an npm dependency?
