### ISSUE TITLE
Slower for "attach" than "launch"?

### ISSUE THREAD

**Issue by roblourens** [microsoft/vscode-node-debug2#195]
Investigating #53785, I noticed that "attach" is taking much longer to start than "launch". Did simple profiling, it seems to be just stuck calling node's `http.get`. No clue why that would be slow. The results loaded in a browser instantly. Investigate this more, see if it's a transient thing or a real problem.

**Comment by connor4312** [comment]
If I'm looking in the right place, this seems to work OK with the latest VS Code and Chrome 77 versions. There's one usage of the `http` module that I can see, [here](https://github.com/microsoft/vscode-chrome-debug-core/blob/b6d3a0435cc687e000a42644ad692bce48537899/src/utils.ts#L278). Wrapping that function in logging, it looks like the requests it makes get executed reasonably quickly and I don't have a noticeable delay on my end.

![image](https://user-images.githubusercontent.com/2230985/66408618-1e134b00-e9a4-11e9-9033-18e8910f4aca.png)

**Comment by roblourens** [comment]
Thanks for testing!
