### ISSUE TITLE
set supportsLoadedSourcesRequest capability if DA implements the request

### ISSUE THREAD

**Issue by weinand** [Microsoft/vscode-node-debug2#199]
The new built-in loaded scripts explorer (which will appear in August) honors the `supportsLoadedSourcesRequest` capability and only shows the "Loaded Scripts" view if the value is true.

Please add this to the `initializeRequest`method:
```ts
	// This debug adapter supports loaded sources request
	response.body.supportsLoadedSourcesRequest = true;
```

This applies to the debug types: `node2`, `extensionHost`,  and `chrome`.

I suggest to include this fix already in July because I will enable the loaded scripts explorer in Insiders as soon as the July release is out of the door.

For details please see https://github.com/Microsoft/vscode/issues/37767

**Comment by weinand** [comment]
@roblourens I see this change in 1.26.8 but no longer in master.
What there a problem with it?

**Comment by roblourens** [comment]
It's also in master, where are you looking?

**Comment by weinand** [comment]
The capability is missing in the current Insiders and this commit removes it:  https://github.com/Microsoft/vscode-node-debug2/commit/a131f4521da93346dfdb261d6dbb71fcda2fa538 
probably because it it now provided by vscode-chrome-debug-core.

**Comment by roblourens** [comment]
This commit from a few days ago put it back: https://github.com/Microsoft/vscode-node-debug2/blob/master/src/nodeDebugAdapter.ts#L78

**Comment by weinand** [comment]
Sorry, but I do not see the `supportsLoadedSourcesRequest` in  https://github.com/Microsoft/vscode-node-debug2/blob/master/src/nodeDebugAdapter.ts#L78:

![2018-08-10_17-16-36](https://user-images.githubusercontent.com/1898161/43966050-2869de1a-9cc1-11e8-9112-aad1970de3b4.png)

**Comment by weinand** [comment]
...and the 1.26 version still uses an older core which doesn't have the capability.

**Comment by roblourens** [comment]
I'll publish that for master now

**Comment by roblourens** [comment]
https://github.com/Microsoft/vscode/commit/271a56a051908db4d91bacbfaf726e1b86305e5c
