### ISSUE TITLE
Error processing "terminate": Error: kill ESRCH

### ISSUE THREAD

**Issue by redsparrowWang** [Microsoft/vscode-node-debug2#201]
Hello, i need help
I got a below error message when reload a debuging program.
![screenshot 2018-09-07 19 24 58](https://user-images.githubusercontent.com/19768895/45213959-0dd9f980-b2d4-11e8-95d7-9ebf12719200.png)

Error processing "terminate": Error: kill ESRCH
    at Object._errnoException (util.js:1024:11)
    at process.kill (internal/process.js:183:18)
    at NodeDebugAdapter.<anonymous> (/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/ms-vscode.node-debug2/out/src/nodeDebugAdapter.js:466:25)
    at Generator.next (<anonymous>)
    at /Applications/Visual Studio Code.app/Contents/Resources/app/extensions/ms-vscode.node-debug2/out/src/nodeDebugAdapter.js:10:71
    at new Promise (<anonymous>)
    at __awaiter (/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/ms-vscode.node-debug2/out/src/nodeDebugAdapter.js:6:12)
    at NodeDebugAdapter.terminate (/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/ms-vscode.node-debug2/out/src/nodeDebugAdapter.js:461:16)
    at Object.<anonymous> (/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/ms-vscode.node-debug2/node_modules/vscode-chrome-debug-core/out/src/chrome/chromeDebugSession.js:102:78)
    at Generator.next (<anonymous>)

![screenshot 2018-09-07 18 43 39](https://user-images.githubusercontent.com/19768895/45213633-11b94c00-b2d3-11e8-8395-e539f1777af1.png)

must stop debuging or press reload button two times, real no idea what happend, could i get some useful infomation at here?

**Comment by redsparrowWang** [comment]
Hi i solved it, pls close.
try to change runtimeExecutable path of launch.json like that
![screenshot 2018-09-07 19 43 21](https://user-images.githubusercontent.com/19768895/45214937-cbfe8280-b2d6-11e8-9e70-2985f45a03b2.png)

**Comment by redsparrowWang** [comment]
Hi, Error processing "terminate": Error: kill ESRCH is solved by change runtimeExecutable path,
but it will be allowed to run multi instance(can't auto close previous instance)，💢
previous, when click the reload button, only one instance, old instance will be auto close.

**Comment by roblourens** [comment]
So when you press reload, the old instance of electron doesn't close, and a second instance opens?

I don't know what the problem would be. What's the difference between the two runtimeExecutable paths, is `/usr/local/bin/electron` a symlink to something?

Does it correctly close the electron instance when you click the stop button?

**Comment by redsparrowWang** [comment]
@roblourens 

Hi, thanks for your reply

>So when you press reload, the old instance of electron doesn't close, and a second instance opens?

yes, old instance doesn't close, and second instance opens, and can to reload more instance by every click reload action.

>I don't know what the problem would be. What's the difference between the two runtimeExecutable paths, is /usr/local/bin/electron a symlink to something?

nope, isn't a symlink link, i had use Atom before and install electron to default path as /user/local/bin/electron. now use VsCode and installed electron on project directory by npm command. i think which one will be working.

/usr/local/bin/electron -version
Electron 2.0.8 - Build cross platform desktop apps with JavaScript, HTML, and CSS

./node_modules/electron/dist/electron.app/Contents/MacOS/electron -version
Electron 2.0.8 - Build cross platform desktop apps with JavaScript, HTML, and CSS

look like same but as my description
/usr/local/bin/electron will be allow multi instance
./node_modules/electron/dist/electron.app/Contents/MacOS/electron will be got error message

below is my project setting, pls confirm it, thank you.

>Does it correctly close the electron instance when you click the stop button?

yes, stop button can be close the electron instance, one click one kill. 

previous, everything is good, realy no idea what happend, 
btw. my VsCode's update setting is all on, it's possible update something on background to make this error? if so is't possible rollback to previous version?


![screenshot 2018-09-11 10 27 56](https://user-images.githubusercontent.com/19768895/45333100-479a5100-b5af-11e8-81bd-98110f15132d.png)

**Comment by roblourens** [comment]
Try the runtimeExecutable in the docs: https://electronjs.org/docs/tutorial/debugging-main-process-vscode

**Comment by redsparrowWang** [comment]
@roblourens 
Hi, thanks for your reply.

I tried, but got other error like that 

![screenshot 2018-09-12 10 40 07](https://user-images.githubusercontent.com/19768895/45396964-ea6ad200-b678-11e8-8ebf-8184053b53d9.png)

>error dialog
runtime can't connect process. timeouted after 10000ms - (reason: can't connect target: connect ECONNREFUSED 127.0.0.1:35814)

>console log
my_path/node_modules/.bin/electron --inspect-brk=35814 . 

(T_T)

**Comment by redsparrowWang** [comment]
About  "runtimeExecutable": "${workspaceRoot}/node_modules/.bin/electron" script.
I tried both by change symlink link, 
![screenshot 2018-09-12 11 11 05](https://user-images.githubusercontent.com/19768895/45398040-a201e300-b67d-11e8-9e8a-581c01568350.png)

"../electron/cli.js" got Error processing "terminate": Error: kill ESRCH
"../electron-prebuilt/cli.js" got  can't connect
(T_T)

**Comment by roblourens** [comment]
If you follow the steps in the docs to set up a sample project, does that work? It does for me.

What version of electron are you using? Can you share your project?

**Comment by redsparrowWang** [comment]
@roblourens 
Hi, thanks very much for your idea.

I tried electron's sample project, working fine.
so i had rebuild my develop environment and check every change in launch.json.

finally, is working. use  "runtimeExecutable": "/usr/local/bin/electron" 

To summarize the conclusion hope can be  help other people.

> "runtimeExecutable": "/usr/local/bin/electron" 
version : Electron 2.0.9 (newest)
error [Error processing "terminate": Error: kill ESRCH : none
dialog [can't connect...] : none
reload button : even if run  "mainWindow.webContents.openDevTools()" no multi instance, 
stop button : fine

> "runtimeExecutable": "/usr/local/lib/node_modules/electron/dist/Electron.app/Contents/MacOS/Electron",

version : Electron 2.0.9 (newest)
error [Error processing "terminate": Error: kill ESRCH : none
dialog [can't connect...] : none
reload button : fine, but "mainWindow.webContents.openDevTools()" will be make multi instance
stop button : one click one instance close

>  "runtimeExecutable": "${workspaceRoot}/node_modules/electron/dist/electron.app/Contents/MacOS/electron",

version : Electron 2.0.0 (like sample )
error [Error processing "terminate": Error: kill ESRCH : none
dialog [can't connect...] : none
reload button : fine, but "mainWindow.webContents.openDevTools()" will be make multi instance
stop button : one click one instance close

> "runtimeExecutable": "${workspaceRoot}/node_modules/.bin/electron",

version : Electron 2.0.0 (like sample )
error [Error processing "terminate": Error: kill ESRCH : none
dialog [can't connect...] : none
reload button : fine, but "mainWindow.webContents.openDevTools()" will be make multi instance
stop button : didn't close instance

First,  Error processing "terminate": Error: kill ESRCH was clear, is my develop environment problem and i'lll be close this issue.

Thanks for your help, thanks a lot　🍺

Best Regards 🍻

**Comment by roblourens** [comment]
I can repro, only debugging electron main with `"console": integratedTerminal`.

**Comment by redsparrowWang** [comment]
yes, you are right, i can't debugging with renderer windows, 
i can attach renderer to main process but breakpoint no response. (T_T)

**Comment by roblourens** [comment]
A fix for this will be in vscode Insiders in about 24 hours

**Comment by redsparrowWang** [comment]
Great! waitting for it, really thanks a lot 🍺

**Comment by redsparrowWang** [comment]
nice, confirmed this fix, good job 🍺

**Comment by redsparrowWang** [comment]
@humorHan 
hi,

i have tried that

1. to confirm development setting or project setting problem
> Try the runtimeExecutable in the docs: https://electronjs.org/docs/tutorial/debugging-main-process-vscode
> make a new project like tutorial, and it working fine, so problem in my setting

2.  in my case tutorial is working fine, so i have to confirm my project setting at .package.json and .vscode/launch.json diff with tutorial setting(i tried to move my source to a new project is worked)

3. finally i confirmed use "runtimeExecutable": "/usr/local/bin/electron" and problem in run "mainWindow.webContents.openDevTools()" or not run it, maybe you should need to try this too.

you know my vscode is auto update, so i can't make sure what happened or upgraded in background, but now it working.

hope this info can be help you, good luck.

**Comment by humorHan** [comment]
It is working well, but when  I press `reload` something occured，I have the same error info with you，and press `reload` again, It is well...
Guess where the configuration is wrong, but never find it.

**Comment by redsparrowWang** [comment]
what about tutorial test ? reload button is working fine ? 
> Try the runtimeExecutable in the docs: https://electronjs.org/docs/tutorial/debugging-main-process-vscode

**Comment by humorHan** [comment]
not electron, I make a custom command，start by npm。as follows
![image](https://user-images.githubusercontent.com/10398024/46656425-9d7b0c80-cbe0-11e8-829e-580d56696000.png)

**Comment by humorHan** [comment]
Do you have this problems?

**Comment by redsparrowWang** [comment]
my case is in electron, but i think 

>If you set "runtimeExecutable": "npm",, your npm script has to set the debug flag. See the examples here: https://code.visualstudio.com/docs/nodejs/nodejs-debugging#_launch-configuration-support-for-npm-and-other-tools

**Comment by redsparrowWang** [comment]
Nodemon Setup: Use nodemon to relaunch a debug session automatically whenever the JavaScript source has changed. Make sure that you have nodemon installed globally. Please note that terminating the debug session only terminates the program to debug, not nodemon itself. To terminate nodemon, press Ctrl+C in the Integrated Terminal.

**Comment by humorHan** [comment]
> Nodemon Setup: Use nodemon to relaunch a debug session automatically whenever the JavaScript source has changed. Make sure that you have nodemon installed globally. Please note that terminating the debug session only terminates the program to debug, not nodemon itself. To terminate nodemon, press Ctrl+C in the Integrated Terminal.

yes，I just see this，It seems to be a bug for me，Or an optimization point.
thank you very much.

**Comment by redsparrowWang** [comment]
maybe need luck, try turn on auto update, good luck. ^_~

>you know my vscode is auto update, so i can't make sure what happened or upgraded in background, but now it working.
hope this info can be help you, good luck.
