### ISSUE TITLE
Debugger fails to reuse breakpoints set in previous session (remote debug)

### ISSUE THREAD

**Issue by remss** [Microsoft/vscode-node-debug2#202]
VSCode Version: 1.27.1

#### On a remote desktop

run: `node --inspect=192.168.0.111:9229 test.js`

```
// test.js
setInterval(() => {
	console.log('hello')
}, 500)
```

#### On your local desktop 

Open VSCode and set a launch target like this in an empty project folder

```
// launch.json
{
    "version": "0.2.0",
    "configurations": [
        {
            "type": "node",
            "request": "attach",
            "name": "Attach",
            "port": 9229,
            "address": "192.168.0.111",
            "localRoot": "${workspaceFolder}"
        }
    ]
}
```
Start a debug "Attach" session
From the LOADED SCRIPTS panel, click on file test.js
The test.js editor tab is open, add a breakpoint at line 3
A breakpoint is added to test.js:3 in the BREAKPOINTS panel
Stop the debug session
Start debug "Attach" session
From the LOADED SCRIPTS panel, click on file test.js

### Actual Result

A second editor tab is open on test.js file , with no breakpoints set in it, and we are paused on line 3.

### Expected Result

The test.js tab from the previous session should be opened, with the same breakpoints, and be paused in it at line 3.

**Comment by remss** [comment]
You are right,. Please test without localRoot nor remoteRoot launch arguments to see the bug.
Please reopen this issue.

**Comment by roblourens** [comment]
For remote debugging, you typically need both localRoot and remoteRoot.

**Comment by roblourens** [comment]
I am adding an error for when just one of localRoot and remoteRoot is specified.
