### ISSUE TITLE
Debugging with local file different from the running one

### ISSUE THREAD

**Issue by remss** [Microsoft/vscode-node-debug2#204]
When we start the debug session and but a breakpoint somewhere, if we make change in that file, the breakpoint is marked as unverified.

But when the runtime hits the breakpoint then we are paused in vscode in the modified file at a line that does not match the running one any more.

Example with a clean file at first:
![image](https://user-images.githubusercontent.com/1586257/45752453-c88fc300-bc15-11e8-84f5-a1cc19e2de4a.png)

Then we add some dummy empty lines, and "continue" debugging. On the next pause we are paused in an empty line
![image](https://user-images.githubusercontent.com/1586257/45752330-60d97800-bc15-11e8-8d8c-86b1d24ce92a.png)

In this case the paused source file should be the running one in read only mode, not the local one, because this is not the same file any more.

**Comment by roblourens** [comment]
I think it's better to just not modify a file while debugging. I think this could add confusion and it would be difficult for us to support this.

**Comment by remss** [comment]
I agree this is the "normal" way to debug. But It is still an issue. If VSCode does not want to support this so it should simply set the edited file in read-only more during a debug session?

Visual Studio C++ debugger handle nicely this problem and VSCode should too IMHO.
