### ISSUE TITLE
vscode   can not reload 

### ISSUE THREAD

**Issue by humorHan** [microsoft/vscode-node-debug2#208]
When I debug nodejs, It is working well, but when I press reload something occured，and press reload again, It is well...
Guess where the configuration is wrong, but never find it.
Because I start my app.js by nodemon？
launch.json
```
{
  "version": "0.2.0",
  "configurations": [
    {
      "name": "dev",
      "type": "node",
      "request": "launch",
      "runtimeExecutable": "npm",
      "runtimeArgs": [
        "run-script",
        "dev"
      ],
      "skipFiles": [
        "${workspaceFolder}/node_modules/**/*.js",
      ],
      "trace": true,
      "timeout": 5000,
      "port": 9229,
      "restart": true,
      "console": "integratedTerminal",
      "internalConsoleOptions": "neverOpen",
      "autoAttachChildProcesses": true
    }
  ]
}
```

**Comment by roblourens** [comment]
> but when I press reload something occured

Can you tell me more about the problem?

**Comment by humorHan** [comment]
> > but when I press reload something occured
> 
> Can you tell me more about the problem?

 only crashed，not reload

```
[nodemon] app crashed - waiting for file changes before starting...
```

**Comment by humorHan** [comment]
And if i save `index.js`, It will restarting multiparty times
```
[nodemon] restarting due to changes...
[nodemon] restarting due to changes...
[nodemon] restarting due to changes...
```

**Comment by roblourens** [comment]
What is that npm script? Can you try with our example nodemon setup?

```json
{
    "type": "node",
    "request": "launch",
    "name": "nodemon",
    "runtimeExecutable": "nodemon",
    "program": "${workspaceFolder}/app.js",
    "restart": true,
    "console": "integratedTerminal",
    "internalConsoleOptions": "neverOpen"
},
```

**Comment by connor4312** [comment]
We have a [new debugger](https://github.com/microsoft/vscode-js-debug/) which deals with nodemon in a more resilient way. Please open an issue there if you still are running into problems.
