### ISSUE TITLE
how to output info in main process (Electron)

### ISSUE THREAD

**Issue by redsparrowWang** [Microsoft/vscode-node-debug2#209]
hello , i have use vscode to develop an electron's nodejs app.
i can use console.log() to outputs something in renderer process(browser console),
but nothing outputs in main process.

run" electron . " in work directory path at terminal, i can see main process outputs in terminal, but i can't see renderer's outputs.

is possible outputs something in main process ? 
(outputs to vscode's debug console or browser console)

or it's electron problem, need to ask electron ?

help pls , thanks

os: mac
electron: using 2.0.9 tried 3.0.9
nodejs: 10.9.0
vscode: 1.28.0

**Comment by roblourens** [comment]
So you are debugging the main process, and you have console.log in the renderer process, and you want to see it in the debug console? Do I understand correctly?

**Comment by roblourens** [comment]
You can see the guide at https://github.com/Microsoft/vscode-recipes/tree/master/Electron to launch the main process then also attach to the renderer process. Then you should be able to see the renderer process's console.logs.

**Comment by roblourens** [comment]
Ok. You can try `"outputCapture": "std"` in your main process launch config to see if that helps. Or `"console": "integratedTerminal"` to just run it in the terminal then you can see it there.

**Comment by redsparrowWang** [comment]
@roblourens 

Thank you very much, got it.
working with "outputCapture": "std" add to main process launch,
i can see main process output in debug console. thanks a lot of

🍺

![screenshot 2018-10-12 15 09 24](https://user-images.githubusercontent.com/19768895/46851149-7c5d2a80-ce31-11e8-8550-a42167362584.png)
