### ISSUE TITLE
[security] This package uses a vulnerable version of event-stream

### ISSUE THREAD

**Issue by mrkev** [Microsoft/vscode-node-debug2#218]
The version in `package.json` could resolve to and install a backdoored version of `event-stream`.

https://github.com/Microsoft/vscode-node-debug2/blob/a1d3fb6f0bc930728b806aa1b4d459ea65ab713c/package.json#L25

See the discussion in the `event-stream` repo for more info: https://github.com/dominictarr/event-stream/issues/116

**Comment by roblourens** [comment]
Thanks for the heads up, but the package-lock.json should prevent that.
