### ISSUE TITLE
Debug type not recognized

### ISSUE THREAD

**Issue by s7dhansh** [Microsoft/vscode-node-debug2#225]
code: 1.30.0
node: 10.14.2

config:
```
{
			"type": "node",
			"request": "launch",
			"name": "Portal: Node",
			"cwd": "${workspaceFolder}/portal",
			"runtimeExecutable": "meteor",
			"runtimeArgs": [
				"npm",
				"run",
				"debug"
			],
			"port": 9229,
			"timeout": 120000,
			"console": "integratedTerminal",
		}
```
gives me an error: `Debug type not recognized`

I had to enable node-debug-legacy to make it work. Can someone help?

**Comment by s7dhansh** [comment]
I meant that with node debug (legacy) extension enabled, it worked.
But ideally node legacy is for node >8 and legacy for lower versions. So this package should have worked, but it didn't. I want to understand the reason.

**Comment by roblourens** [comment]
The extensions are linked and lots of shared code is actually in the "legacy" extension. So you should not disable it.
