### ISSUE TITLE
All Node.js breakpoints do not work and show as "unverified breakpoint"

### ISSUE THREAD

**Issue by afefer** [Microsoft/vscode-node-debug2#226]
Issue Type: <b>Bug</b>

Node.js debugging fails with v1.31.0-insider (but works fine with non-Insider 1.30.1) and all breakpoints are greyed-out hollow circle with "Unverified Breakpoint" as hover-over message. Despite breakpoints not working, debugging appears to start normally. Source files are TypeScript, Project node.js version is 6.10.3, with the debug script running via WSL.

Details on both installs below:

Non-working version:
Version: 1.31.0-insider (system setup)
Commit: e02e44464c02d617b98d0a3265bf5efef7794436
Date: 2018-12-21T06:20:35.852Z
Electron: 3.0.10
Chrome: 66.0.3359.181
Node.js: 10.2.0
V8: 6.6.346.32
OS: Windows_NT x64 10.0.17134

Working version:
Version: 1.30.1 (system setup)
Commit: dea8705087adb1b5e5ae1d9123278e178656186a
Date: 2018-12-18T18:12:07.165Z
Electron: 2.0.12
Chrome: 61.0.3163.100
Node.js: 8.9.3
V8: 6.1.534.41
OS: Windows_NT x64 10.0.17134

VS Code version: Code - Insiders 1.31.0-insider (e02e44464c02d617b98d0a3265bf5efef7794436, 2018-12-21T06:20:35.852Z)
OS version: Windows_NT x64 10.0.17134

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-6600K CPU @ 3.50GHz (4 x 3504)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|15.94GB (8.14GB free)|
|Process Argv||
|Screen Reader|no|
|VM|67%|

</details>Extensions: none

**Comment by roblourens** [comment]
Not much has changed since 1.30. Could you set `"trace": true`, run it again, and upload the log here?

**Comment by afefer** [comment]
Yup - see attached [debugadapter.txt](https://github.com/Microsoft/vscode-node-debug2/files/2719895/debugadapter.txt)

**Comment by roblourens** [comment]
Does the file in `.build/endpoints/OrgsEndpoint.js` actually exist on disk or is it served from webpack-dev-server or something like that?

**Comment by afefer** [comment]
All the files in .build/ actually exist on disk.
