### ISSUE TITLE
[loc][Query][vscode_extensions ] Localizability of 0; "package.extensionHost.launch.config.name"

### ISSUE THREAD

**Issue by PDostalek** [Microsoft/vscode-node-debug2#229]
Hi,
please help localization team to answer question from translator.
In case translator is not sure about context/meaning/localizability of string we raise a question to Core team.
Please re-assign back to use in case you are not the right contact person or you can´t assign to a proper person.
Can you help please?
Thanks!

Source:
Launch Extension

File Name:
Src\vscode-extensions\vscode-node-debug2.xlf

Resource ID:
0; "package.extensionHost.launch.config.name"

Query:
Is Launch a verb here?

**Comment by roblourens** [comment]
Yes it is

**Comment by PDostalek** [comment]
Thanks!
