### ISSUE TITLE
[loc][Query][vscode_extensions ] Localizability of  0; "out/src/nodeDebugAdapter.node.console.title"

### ISSUE THREAD

**Issue by PDostalek** [Microsoft/vscode-node-debug2#230]
Hi,
please help localization team to answer question from translator.
In case translator is not sure about context/meaning/localizability of string we raise a question to Core team.
Please re-assign back to use in case you are not the right contact person or you can´t assign to a proper person.
Can you help please?
Thanks!

Source:
Node Debug Console

File Name:
Src\vscode-extensions\vscode-node-debug2.xlf

Resource ID:
0; "out/src/nodeDebugAdapter.node.console.title"

Query:
Does Node refer to the open source platform and, therefore, it is not translatable? Or is it a generic term and we can translate?

**Comment by roblourens** [comment]
Yes Node refers to Node.js and should not be translated.
