### ISSUE TITLE
Releases do not contain vsix extention

### ISSUE THREAD

**Issue by ibuziuk** [microsoft/vscode-node-debug2#232]
The latest stable releases e.g. https://github.com/Microsoft/vscode-node-debug2/releases/tag/v1.33.0 do not contain vsix files
Will it be possible to add vsix files to the latest and upcoming releases similar to what is done for other extentions e.g. python https://github.com/Microsoft/vscode-python/releases

**Comment by roblourens** [comment]
Why?

**Comment by ibuziuk** [comment]
for our particular case to avoid marketplace rate limit error - https://github.com/eclipse/che/issues/12840
In general, it looks like a good practice e.g. https://github.com/Microsoft/vscode-python/releases 
having only sources in the release does not make much sense IMO

**Comment by nickboldt** [comment]
Additionally, Microsoft has said that we're not supposed to link directly to marketplace.visualstudio.com anymore for vscode extensions used outside VS Code itself.

So to use these plugins in Che, we need them published to github releases (or some other place).

See also https://github.com/eclipse/che/issues/14573

**Comment by connor4312** [comment]
We now have a [new debugger](https://github.com/microsoft/vscode-js-debug/) and do not expect m/any more releases of this one.
