### ISSUE TITLE
Node debugger not closing ports after running

### ISSUE THREAD

**Issue by danielleIdehenWork** [microsoft/vscode-node-debug2#234]
Hi,

When I run the debugger, then close it and run it again i get an error saying that  
...
throw er; // U
nhandled 'error' event
      ^

Error: listen EADDRINUSE: address already in use :::11006
...

Then when i manually find the PID for that port then close the port and run the program runs fine, then when I refresh the error returns.
I have to manually close the port the program is running on after everytime  I run the debugger, 
This problem started somepoint early/mid last week, 
 
Please can someone offer some insight as to why the debugger is no longer closing ports properly after it runs?

Thanks

**Comment by roblourens** [comment]
It sounds like your app process is still alive after the debugger stops, is that right? Can you figure out whether it's a process spawned by your program, or whether it's your program's main process?

**Comment by danielleIdehenWork** [comment]
Hi,

Yes that’s right, yes I think the process is started by my program however my program closes it,
This problem only started last week and up until that point i was running the same code with no problems,
I cannot share my launch config at this point,
What sort of set up details do you need?

Thanks,

Danielle Idehen
Mobile: +44(0)2033357570
30 Fenchurch Street, London EC3M 3BD
________________________________
This message is for the designated recipient only and may contain privileged, proprietary, or otherwise private information. If you have received it in error, please notify the sender immediately and delete the original. Any other use of the e-mail by you is prohibited. Where allowed by local law, electronic communications with Accenture and its affiliates, including e-mail and instant messaging (including content), may be scanned by our systems for the purposes of information security and assessment of internal compliance with Accenture policy.

Accenture means Accenture (UK) Limited (registered number 4757301), registered in England and Wales with registered address at 30 Fenchurch Street, London EC3M 3BD.

**Comment by roblourens** [comment]
There have been no vscode updates in that time so it sounds like it must be an issue with your program. Make sure that you shut down any processes that you spawn. The debugger doesn't do anything with ports that your app uses.

**Comment by connor4312** [comment]
We now have a [new debugger](https://github.com/microsoft/vscode-js-debug/) which attaches to the program in a different way. without needing particular ports, so that should resolve this issue. Please open a new issue on that repo if not.
