### ISSUE TITLE
Debugger (Node --inspect) metadata access outside of VSCode (ie from Chrome DevTools)

### ISSUE THREAD

**Issue by june07** [microsoft/vscode-node-debug2#236]
This is being opened per being recommended by roblourens in https://github.com/microsoft/vscode-node-debug2/pull/235

@roblourens Thank you very much for your insightful feedback.  Before beginning any work on writing this, I just want to be clear that there is currently no other known way to access Node.exe metadata (ie --inspect) that comes baked into VSCode?

Further in order to achieve such functionality, it has been suggested to use the DebugAdapterTracker API to write a VSCode extension that adds this feature?

I assume that in using that API, it would then be possible to publish said data openly such that no other requirements are needed to access it on the receiving end (ie, a simple http access).  Basically, what I've already done will need to be adapted to a VSCode extension vs being built in.

**Comment by roblourens** [comment]
Yes, correct. Pasting my response here just to make it easier to find later:

> I think that being able to open chrome devtools on the process you are attached to in vscode would be really useful. It would be nice to have an extension that can provide that feature. I don't really think that starting a webserver from the debug adapter is the right way to do it.
>
> What you can do is use the DebugAdapterTracker API to watch for console messages from a node debug session of the pattern "Debugger listening on ws://127.0.0.1:9876/a92b13de-b2ba-4318-9c3e-3221bbbb218f". Then your extension will know how to open chrome devtools. Please open an issue to discuss if you need anything more from the debug adapter.

**Comment by roblourens** [comment]
Since this can be implemented by an extension, I am going to close this

**Comment by june07** [comment]
For those interested (working VSCode extension v0.0.1):
https://marketplace.visualstudio.com/items?itemName=June07.nims
https://github.com/june07/NiMS-vscode-extension

**Comment by roblourens** [comment]
FYI @weinand, an application of `DebugAdapterTracker`
