### ISSUE TITLE
Publish as dedicate node module

### ISSUE THREAD

**Issue by mickaelistria** [microsoft/vscode-node-debug2#239]
This debug adapter can be reused by other IDEs and editors. To make it easier to consume, it would be great to have it published on npm.js as a dedicated module.
Current workaround involves either building from source or extracting it from VSCode delivery.

**Comment by connor4312** [comment]
This debugger [has been superceded](https://github.com/microsoft/vscode-js-debug/) and is not expected to receive m/any more updates.
