### ISSUE TITLE
setting a variable from console doesn't update variables view

### ISSUE THREAD

**Issue by jrieken** [Microsoft/vscode-node-debug2#24]
* stop on a breakpoint have a variable `c = 101`
* on the debug console write `c = 32`
* on the console write `c` and see that the value has been updated
* 🐛 the variables view still shows the old value

![screen shot 2016-09-27 at 12 35 53](https://cloud.githubusercontent.com/assets/1794099/18869982/f241e566-84ae-11e6-9bcd-21bc5009010d.png)

**Comment by roblourens** [comment]
vscode doesn't support this :(, chrome devtools has the same behavior
