### ISSUE TITLE
Breakpoints do not work in remote wsl session

### ISSUE THREAD

**Issue by jason076** [microsoft/vscode-node-debug2#240]
I am running a remote wsl session with the new remote wsl plugin and try to debug a node application, but all breakpoints are displayed as unverified and the program does not halt. If I activated the checkbox that the debugger should halt on every exception the programm pauses correctly and I can single step through the code.

My launch.json:

````{
    "version": "0.2.0",
    "configurations": [
        {
            "type": "node",
            "request": "launch",
            "name": "Debug server",
            "console": "internalConsole", 
            "outputCapture": "std",
            
            //"preLaunchTask": "build",
            "runtimeExecutable": "npm",
            "runtimeArgs": [
                "run-script",
               "debug_vs"
            ],
            "sourceMaps": true,
            "port": 9229,
            //"skipFiles": ["<node_internals>/**/*.js"]
        }
    ]
}
````

**Comment by jason076** [comment]
I have figured out the cause of this issue. I have stored the project files in the windows file system and created a symbolic link to it from within the wsl filesystem. The symbolic link seems to break something. 
I have copied the project files to the wsl filesystem now and the debugging works as expected.

**Comment by roblourens** [comment]
Glad you were able to figure it out. This will probably help if you want to continue using symlinks: https://code.visualstudio.com/docs/nodejs/nodejs-debugging#_can-i-debug-if-im-using-symlinks
