### ISSUE TITLE
[Question] handling of files <node_internals>

### ISSUE THREAD

**Issue by yyoncho** [microsoft/vscode-node-debug2#241]
Hi, I am the maintainer of https://github.com/emacs-lsp/dap-mode which is the Emacs client of the debug adapter protocol. I am writing a view which will display the loaded sources and I noticed that some of the files comming from this adapter are prefixed with `<node_internals>`. Can you point me to a resource which I can use as a guide for implementing the handling of these files?

**Comment by roblourens** [comment]
Can you explain what you mean by "handling"? These are just files which the debug adapter has guessed are probably node's files. We just add that for files loaded without an absolute path.

**Comment by yyoncho** [comment]
@roblourens thanks for the quick reply. In vscode when you click this file it is opened in the editor. I want to replicate that behaviour in emacs but it is unclear to me how to find that file. Excuse my ignorance, I am not very familiar with node internals.

**Comment by roblourens** [comment]
I see. The client doesn't need to know anything about node internals, that's what the debug adapter is for :)

These files will be sent with a sourceReference:

https://github.com/microsoft/vscode-debugadapter-node/blob/df24f9770344b5c79c8e9e34cfee03c47f7f38f9/protocol/src/debugProtocol.ts#L1510

And you can request the source of that script by sending a `sources` request for that sourceReference:

https://github.com/microsoft/vscode-debugadapter-node/blob/df24f9770344b5c79c8e9e34cfee03c47f7f38f9/protocol/src/debugProtocol.ts#L983

And the adapter knows how to retrieve it from node. Hope that helps

**Comment by yyoncho** [comment]
Thank you and sorry for bothering you - I should have spent more time reading the spec!
