### ISSUE TITLE
Support BreakpointLocations request

### ISSUE THREAD

**Issue by isidorn** [microsoft/vscode-node-debug2#242]
We added support for this on the vscode side could you look into adding support for the `breakpointLocationRequest` for node2? It would be very cool if we get this.

Let me know if you need help with this.

Refs https://github.com/microsoft/vscode/issues/31612

**Comment by roblourens** [comment]
![image](https://user-images.githubusercontent.com/323878/65378034-15164000-dc68-11e9-89f5-8f3a61a50a7a.png)

This is awesome. I'll try to get it in for this month but can't promise it.

**Comment by isidorn** [comment]
Glad you like it! Yeah let me know if you don't get time and if I can help somehow.

**Comment by isidorn** [comment]
@roblourens Great! Thanks for adding this. I'll give it a try today.
Also here's the test plan item which I created https://github.com/microsoft/vscode/issues/81175
Feel free to edit it.

**Comment by isidorn** [comment]
This works fine. Adding verified label.
