### ISSUE TITLE
An error displays in the debug console during a debug session.

### ISSUE THREAD

**Issue by georgeben** [microsoft/vscode-node-debug2#249]
While debugging a Node.js app using the Node.js debugger, the following error message popped up. I haven't been able to reproduce the error yet.
<img width="1291" alt="Screen Shot 2019-11-11 at 4 14 12 PM" src="https://user-images.githubusercontent.com/40215996/68600291-89b86e80-04a2-11ea-98a3-879404378536.png">

**Comment by roblourens** [comment]
https://github.com/microsoft/vscode-chrome-debug-core/issues/535
