### ISSUE TITLE
Feature request: Support sourcemap updates when live-editing files

### ISSUE THREAD

**Issue by MSLaguana** [Microsoft/vscode-node-debug2#25]
In our react-native debugger (uses the node debugger internally) one scenario we require is being able to edit the sourcecode and have it take effect almost immediately. We currently handle the source code changes just fine, but updating source maps requires additional work. Currently we have some invasive logic to manually clear the source map cache of the debugger, but it'd be great if the debugger itself could somehow notice that the sourcemap file has been updated.

**Comment by roblourens** [comment]
Can you link me to the code that clears the sourcemap cache?

**Comment by MSLaguana** [comment]
This is how we do it currently: https://github.com/Microsoft/vscode-react-native/blob/master/src/debugger/nodeDebugWrapper.ts#L195

We set up a server that waits to be told to nuke the breakpoints, then it invasively clears the cached sourcemaps and requests that vscode re-send them.

**Comment by roblourens** [comment]
I think this would have been fixed with the bug in -core.
