### ISSUE TITLE
Debugger never hits test code when using rush repo

### ISSUE THREAD

**Issue by beejones** [microsoft/vscode-node-debug2#251]
I created a repo to reproduce the problem: https://github.com/beejones/rush-test-environment.

Please open https://github.com/beejones/rush-test-environment/blob/master/libs/sample-package/tests/Calculator.spec.ts.
Put a break point on line 6.
Pressing F5 launches the debugger but it closes after a few seconds and the console has not error.
If I enable all/uncaught Exceptions, nothing gets triggered.

For debugging, I am using this launch.json:  https://github.com/beejones/rush-test-environment/blob/master/.vscode/launch.json.
This setup uses the node_modules from sample-package.

In the log file, I see that packages are used on/common/temp/node_modules. I am not sure this is the reason. See:
 ← From target: {"method":"Debugger.scriptParsed","params":{"scriptId":"54","url":"file:///C:/did1/rush-test-environment/common/temp/node_modules/...

I tested this on node v12.13 and v10.16 and rush v5.3.

I also tried to set NODE_PATH to the sample-package but this had no impact.
Is it possible to clone the repo. The readme has the instruction how to install rush.
Thanks

**Comment by roblourens** [comment]
I don't think your launch config is actually running your tests. When I try running the command manually, I just get `No specs found`. Sorry, I don't know how jasmine-ts is supposed to be called.

**Comment by beejones** [comment]
To run the tests manually you can do:
cd sample-package
node .\node_modules\jasmine-ts\lib\index --config=.\tests\jasmine.json   .\tests\Calculator.spec.ts

or

npm run test

Jasmine started

  Calculator
    √ should add numbers (0.003 sec)

Executed 1 of 1 spec SUCCESS in 0.07 sec.

**Comment by beejones** [comment]
Sorry accidentally closed the issue.

**Comment by roblourens** [comment]
Looks like you just need to set `"cwd": "${workspaceFolder}/libs/sample-package"` so it runs in the same directory as your manual example

**Comment by beejones** [comment]
Thanks. I updated the repo so it might help others with the same debugging problem.
