### ISSUE TITLE
Node debug skips certain source files

### ISSUE THREAD

**Issue by AnthonyWeston** [microsoft/vscode-node-debug2#252]
### Summary
When I run a Node debug session, it skips over a file in my project as if it were explicitly skipped using VSCode's `skipfiles` config option. I can't identify any obvious reason why it's doing this for one file and not the others I'm working with currently, and my current workaround is to revert back to 1.39.3, as this is the latest version available that doesn't have this behavior. I was previously using 1.42.0.

I'm including some information below that I think/hope might be helpful. Let me know if I need to add anything else.

### Node/npm versions
Node: 10.16.0
npm: 6.13.0

### Extension info for the most recent working version:
Name: Node Debug
Id: ms-vscode.node-debug2
Description: Node.js debugging support
Version: 1.39.3
Publisher: Microsoft
VS Marketplace Link: https://marketplace.visualstudio.com/items?itemName=ms-vscode.node-debug2

### Enabled extensions

Extension | Author (truncated) | Version
-- | -- | --
Bookmarks | ale | 10.6.0
vscode-eslint | dba | 2.0.11
xml | Dot | 2.5.0
gitlens | eam | 10.2.0
docthis | joe | 0.7.1
binary-viewer | mom | 0.0.1
vscode-docker | ms- | 0.9.0
python | ms- | 2019.11.50794
node-debug2 | ms- | 1.39.3
vetur | oct | 0.22.6
indent-rainbow | ode | 7.4.0
java | red | 0.55.1
partial-diff | ryu | 1.4.0
markdown-preview-enhanced | shd | 0.5.0
vscode-checkstyle | she | 1.3.2
vscodeintellicode | Vis | 1.2.2
vscode-java-debug | vsc | 0.24.0
vscode-java-dependency | vsc | 0.6.0
vscode-java-pack | vsc | 0.8.1
vscode-java-test | vsc | 0.22.0
vscode-maven | vsc | 0.20.1
markdown-all-in-one | yzh | 2.6.1

**Comment by roblourens** [comment]
Could you set `"trace": true` in your launch config, reproduce the issue, then upload the log from the path in the debug console here?

**Comment by AnthonyWeston** [comment]
Is this what you need?

[debugadapter.txt](https://github.com/microsoft/vscode-node-debug2/files/4031834/debugadapter.txt)

**Comment by roblourens** [comment]
Yes, thanks. Could you tell me where it skipped that it shouldn't have in that run? Also could you check whether setting `"smartStep": false` in your config fixes it?

**Comment by AnthonyWeston** [comment]
It was skipping over `commands.js`, which is being run from the jest test suite in `commands.spec.js`. I tried setting `"smartStep": false` with the newest version, and it works.

**Comment by AnthonyWeston** [comment]
[debugadapter-smartstep-false.zip](https://github.com/microsoft/vscode-node-debug2/files/4032183/debugadapter-smartstep-false.zip)

**Comment by roblourens** [comment]
Ok. That means that the line that it stepped to does not have a sourcemapping associated with it. It could mean that there is something weird going on with the sourcemaps. If you can share that commands.js file and its sourcemap, I might be able to tell you more.

You could also try this new debug extension: https://marketplace.visualstudio.com/items?itemName=ms-vscode.js-debug-nightly it is a new implementation and the future of vscode JS debugging

**Comment by AnthonyWeston** [comment]
I'm not sure if I'm able to share the source code or source map. How would I go about determining whether the source file has a source map associated with it? We use webpack and babel if that matters.

I added the debug extension, and it works just fine now.

**Comment by roblourens** [comment]
> I added the debug extension, and it works just fine now.

That's great! I would recommend just sticking with that, it will become the default eventually.
