### ISSUE TITLE
req.cookies

### ISSUE THREAD

**Issue by yaghobieh** [microsoft/vscode-node-debug2#253]
Issue Type: <b>Bug</b>

req.cookies.token return undifined
How I can use it?

Extension version: 1.33.0
VS Code version: Code 1.41.1 (26076a4de974ead31f97692a0d32f90d735645c0, 2019-12-18T14:58:56.166Z)
OS version: Windows_NT x64 10.0.18362

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-4510U CPU @ 2.00GHz (4 x 1995)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off<br>surface_control: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|7.91GB (1.33GB free)|
|Process Argv|.|
|Screen Reader|no|
|VM|0%|
</details>

**Comment by yaghobieh** [comment]
res.cookie('token', token, { httpOnly: true }).sendStatus(200);
and for get 
req.cookies.token

**Comment by connor4312** [comment]
This is a good question for the [Express community on StackOverflow](https://stackoverflow.com/questions/tagged/express), as it's not related to the debug adapter.
