### ISSUE TITLE
'${workspaceFolder}' can not be resolved in a multi folder workspace

### ISSUE THREAD

**Issue by YunHsiao** [microsoft/vscode-node-debug2#256]
This is a repeatedly emerging regression issue, first reported at https://github.com/microsoft/vscode/issues/94725.

AFAIK, both 1.44.4 and the current latest 1.44.7 have this issue, I tried installing 1.44.6 in the lastest VSCode release(1.47.2) and it worked fine again. (my `launch.json` has never changed the whole time)

Basically all the debug tasks under any multi-root workspace are blocked by this:
```js
            {
                "type": "node",
                "request": "launch",
                "name": "Build Effects",
                "program": "${workspaceRoot:editor}/tasks/effect.js",
            }
```

Please investigate and hope that we can never again see this issue coming back.

**Comment by connor4312** [comment]
Does setting the configuration `type` to `pwa-node` work for you?

**Comment by YunHsiao** [comment]
Oh.. Seems I missed the more recent bug report (https://github.com/microsoft/vscode/issues/102162), it works, thank you.

TBH this regression behavior has been a really painful exprerience, but immediate feedback like this is much appreciated.
Keep up the good work!
