### ISSUE TITLE
Debug launch should gracefully fail on older versions of Node

### ISSUE THREAD

**Issue by mousetraps** [Microsoft/vscode-node-debug2#26]
Testing https://github.com/Microsoft/vscode/issues/12600

Node v6.2.1 x64 on Windows attempts to run:
`node --inspect=13471 --debug-brk --nolazy server.js`

**Expected:** helpful and actionable error message about an unsupported version

**Actual:** debug fails with following cryptic message to debug console

```
node --inspect=9286 --debug-brk --nolazy server.js 
node: bad option: --inspect=9286
```

**Comment by mousetraps** [comment]
Ooh, actually v6.3.1 is supported - updating this issue to reflect the actual error message printed w/ older versions of node, and creating another issue to track the v6.3 issue
https://github.com/Microsoft/vscode-node-debug2/issues/27

**Comment by roblourens** [comment]
Yeah I was trying to decide whether to query `node --version` and try to tell the user that it won't be supported, or detect that exact output in stderr and give something better, or leave it up to the user. Can probably do better.

**Comment by roblourens** [comment]
I'm going to close this for now because it just adds complexity to the startup process, and can't handle things like 'attach' anyway, but if lots of people complain maybe we'll have to do something about it. Or when it's no longer 'experimental'.

**Comment by mousetraps** [comment]
@roblourens this seems like something that should definitely be addressed when it moves out of being experimental (ppl don't upgrade node versions that frequently), so not sure what good it does to push the work fwd. If it adds complexity, it would probably be best to get as much testing as possible before it becomes official.

**Comment by roblourens** [comment]
Yeah let's reopen it. It has definitely come up in node-debug issues where we've been encouraging people to try node2.

**Comment by roblourens** [comment]
Now that it's no longer 'experimental', we expect people to use the 'auto' option, which makes this hopefully not a problem.
