### ISSUE TITLE
When will the initialized event be sent？

### ISSUE THREAD

**Issue by pengsongkun741** [microsoft/vscode-node-debug2#261]
Hello, I received a response from the server when I tried to initialize the debug adapter. But did not receive the initialization event.
Through DAP, I learned that the initialization event must be received before I can start sending other requests.
This is all the information I got after sending the initialization request.Through attach debugging methods, it is found that there is no send the initialization event.
Are there any steps I am missing?
Thanks!

![初始化返回信息](https://user-images.githubusercontent.com/61906325/110913986-c2937c80-8350-11eb-8ce8-dad11f2d8f3a.PNG)

**Comment by roblourens** [comment]
Is this a DAP question or are you trying to run this debug adapter yourself?

**Comment by pengsongkun741** [comment]
I use the Omnisharp.Extension.DebugAdapter component developed by the Omnisharp team. You can find this package directly on Nuget.
This is a record of my communication with the Omnisharp team:
https://github.com/OmniSharp/csharp-language-server-protocol/issues/486

After sending the initialize request and listening for the output of the debug adapter, I did not receive the initialized event transmission. Through the Dap protocol, after the client sends an initialization request and receives an initialization response, the server will actively send an initialization event.

**Comment by roblourens** [comment]
Sorry I still don't understand, so you are having a problem with the omnisharp debug adapter?

**Comment by pengsongkun741** [comment]
Please allow me to describe my problem again:
Omnisharp has a client based on the DAP protocol, which can be used to call the debug adapter.
I use Omnisharp's tool to communicate with the `vscode-node-debug2` debug adapter.
But encountered a problem in the process of sending the `initialize request`.

Ideally, after I send the `initialize request`. The `vscode-node-debug2` debug adapter will send me the `initialize response` data and `initialized event` back to me.
But in the actual situation, I only received the `initialize response` data, and did not receive the `initialized event`.

This is send request  json:
```
Content-Length: 137

{"seq":1,"type":"request","command":"initialize","arguments":{"adapterID":"nodejs","pathFormat":"path","supportsProgressReporting":true}}
```
This is received response json:
```
Content-Length: 738


{
    "seq": 1,
    "type": "response",
    "request_seq": 1,
    "command": "initialize",
    "success": true,
    "body": {
        "exceptionBreakpointFilters": [
            {
                "label": "All Exceptions",
                "filter": "all",
                "default": false
            },
            {
                "label": "Uncaught Exceptions",
                "filter": "uncaught",
                "default": false
            }
        ],
        "supportsConfigurationDoneRequest": true,
        "supportsSetVariable": true,
        "supportsConditionalBreakpoints": true,
        "supportsCompletionsRequest": true,
        "supportsHitConditionalBreakpoints": true,
        "supportsRestartFrame": true,
        "supportsExceptionInfoRequest": true,
        "supportsDelayedStackTraceLoading": true,
        "supportsValueFormattingOptions": true,
        "supportsEvaluateForHovers": true,
        "supportsLoadedSourcesRequest": true,
        "supportsBreakpointLocationsRequest": true,
        "supportsLogPoints": true,
        "supportsTerminateRequest": false
    }
}
```

The DAP protocol stipulates that the `initialized event` of the debug adapter must be received before sending other requests.

Omnisharp toolbox I use also defines this. Therefore, I cannot do anything until I receive the `initialized event`.

Is there any problem with the request data I sent?

**Comment by roblourens** [comment]
Ok, so you are trying to use this debug adapter with some other client. So this debug adapter is actually not under development anymore. VS Code has moved to this implementation: https://github.com/microsoft/vscode-js-debug I recommend you try with that one.
