### ISSUE TITLE
Debugger doesn't *actually* support 6.3.0?

### ISSUE THREAD

**Issue by mousetraps** [Microsoft/vscode-node-debug2#27]
Testing https://github.com/Microsoft/vscode/issues/12600

Contrary to v6.3.0 release notes... https://nodejs.org/en/blog/release/v6.3.0/

With Node v6.3.0 (32-bit) on Windows, VSCode attempts to run:
node --inspect=13471 --debug-brk --nolazy server.js 

**Expected:** debugger attaches successfully

Instead prints gobligook message to debug console
`Cannot connect to runtime process, timeout after 10000 ms - (reason: Response from the target seems invalid: [ { "description": "node.js instance", "devtoolsFrontendUrl": "https://chrome-devtools-frontend.appspot.com/serve_file/@521e5b7e2b7cc66b4006a8a54cb9c4e57494a5ef/inspector.html?experiments=true&v8only=true&ws=localhost:13471/node", "faviconUrl": "https://nodejs.org/static/favicon.ico", "id": "1468", "title": "C:\Program Files\nodejs\node.exe", "type": "node", "webSocketDebuggerUrl":```

**Comment by roblourens** [comment]
Is that the whole error message, so webSocketDebuggerUrl is empty? That would be a problem. Windows support is sketchy

**Comment by mousetraps** [comment]
That's all I could copy from the infobar, so there might be more text, but I couldn't see it.

**Comment by roblourens** [comment]
Not sure what happened here, but it would be an issue on Node's end.
