### ISSUE TITLE
Occasional `[node-debug2] read ECONNRESET` on Windows w/ Node v6.6.0 (32-bit)

### ISSUE THREAD

**Issue by mousetraps** [Microsoft/vscode-node-debug2#28]
Testing https://github.com/Microsoft/vscode/issues/12600

Running against Node v6.6.0 (32-bit), after launching the debugger successfully several times in a row, saw this error in the infobar:
`[node-debug2] read ECONNRESET`

And this error to the debug console:
```
node --inspect=28101 --debug-brk --nolazy server.js 
Debugger listening on port 28101.
Warning: This is an experimental feature and could change at any time.
******** Error in DebugAdapter - Unhandled promise rejection: Error: read ECONNRESET
    at exports._errnoException (util.js:1026:11)
```

Will provide further details if I manage to come up with a better repro

**Comment by mousetraps** [comment]
FWIW shortly after, tried running again, and received:
```
node --inspect=4001 --debug-brk --nolazy server.js 
Unable to open devtools socket: address already in use
```

didn't seem to see lingering processes in Task manager, so not sure what's up

**Comment by roblourens** [comment]
That time it might just be that we picked a random process id that was already claimed since we don't check whether it's in use (node-debug does the same thing)

**Comment by mousetraps** [comment]
Verbose logs: 
[vscode-node-debug2.txt](https://github.com/Microsoft/vscode-node-debug2/files/496681/vscode-node-debug2.txt)

**Comment by roblourens** [comment]
Anything in the command prompt when you get econnreset? Did Node crash with that assert?
