### ISSUE TITLE
Occasional debug fails to start w/o message on Windows w/ Node v6.6.0 (32-bit)

### ISSUE THREAD

**Issue by mousetraps** [Microsoft/vscode-node-debug2#29]
Testing Microsoft/vscode#12600
Occasionally, debugging fails to launch w/o much indication as to why.

F5 to launch, debug bar flashes, then quickly disappars as the following message is printed to the debug console:
```
node --inspect=6952 --debug-brk --nolazy server.js 
Debugger listening on port 6952.
Warning: This is an experimental feature and could change at any time.
```

will update w/ better repro steps if available, but might be good to add some better logging to account for issues like this in the future

**Comment by roblourens** [comment]
Can you set 'verboseDiagnosticLogging': true in your launch config next time? There will probably be some error

**Comment by roblourens** [comment]
Probably a crash same as #38. The assert message doesn't go to stderr so I'm not sure how to show more info in the debug console.
