### ISSUE TITLE
Locals window visualization not updated properly

### ISSUE THREAD

**Issue by mousetraps** [Microsoft/vscode-node-debug2#30]
Testing Microsoft/vscode#12600

Node v6.6.0 (32-bit), Windows

**Expected:** glorious magical blue flash of happiness in the Locals window as you step over the variable assignment
![image](https://cloud.githubusercontent.com/assets/762848/18887384/b75415b0-84a8-11e6-8f9b-98b3b5b23248.png)

**Actual:** sadness.
![image](https://cloud.githubusercontent.com/assets/762848/18887444/ffc78390-84a8-11e6-9556-dab816d9be80.png)

**Comment by roblourens** [comment]
How does that even work...
