### ISSUE TITLE
Usage of `externalConsole` property should be marked as deprecated rather than `not allowed`

### ISSUE THREAD

**Issue by mousetraps** [Microsoft/vscode-node-debug2#32]
Testing Microsoft/vscode#12600

**Expected**
![image](https://cloud.githubusercontent.com/assets/762848/18888103/c87fae46-84ab-11e6-99e0-90b3da4f67ee.png)

**Actual**
![image](https://cloud.githubusercontent.com/assets/762848/18888060/a1940584-84ab-11e6-91f0-61e668d58050.png)

**Comment by roblourens** [comment]
Since it's deprecated in node-debug, I'd rather just not support it in a new debug adapter, rather than taking it now and just removing it later anyway. That was Andre's opinion too.
