### ISSUE TITLE
Node process never exits while debugger attached

### ISSUE THREAD

**Issue by mousetraps** [Microsoft/vscode-node-debug2#33]
Testing Microsoft/vscode#12600

Node v6.6.0 (32-bit), Windows

Repro steps - launch.json configured to launch `app.js`
```js
/* app.js */
setTimeout(function() {
    console.log('done');
    process.exit();
},1000)
````

**Expected:** process exits after 1s
**Actual:** process never exits
![image](https://cloud.githubusercontent.com/assets/762848/18890689/10d5a26c-84b7-11e6-9d7d-fe8cc8293a59.png)

**Comment by mousetraps** [comment]
Also looked into whether this was a Node issue or a VSCode issue... `node --inspect --debug --nolazy app.js` exits properly, so I suspect it's an issue on our end.

**Comment by mousetraps** [comment]
Also looked into whether this was a Node issue or a VSCode issue... `node --inspect --debug-brk --nolazy app.js` does not exit properly w/ chrome debug tools (in that case, it returns the additional error message: "Waiting for the debugger to disconnect..."), so I suspect it's an issue on Node's end. Not sure why this message didn't get printed in VSCode, though

**Comment by roblourens** [comment]
I would also expect that message to be printed. I usually see it...

This is https://github.com/Microsoft/vscode-node-debug2/issues/11 :(
