### ISSUE TITLE
Hovering over argument with same name as outer variable produces nothing

### ISSUE THREAD

**Issue by mousetraps** [Microsoft/vscode-node-debug2#34]
Testing Microsoft/vscode#12600

Using the following code and a breakpoint at the location specified location
```js
var screenName = 'hello';

setTimeout(function() {
    console.log('done');
    a(screenName);
    
    process.exit();
},1000)

function a(screenName) {
    console.log(screenName); // SET BREAKPOINT HERE
}
````

hovering over screenName at this position should produce the string `"hello"`, instead, no hover appears. Changing the name of the argument resolves the issue.

**Comment by roblourens** [comment]
This issue was moved to Microsoft/vscode#12952
