### ISSUE TITLE
Occasional debug timeout issue during attach to process

### ISSUE THREAD

**Issue by mousetraps** [Microsoft/vscode-node-debug2#38]
Testing https://github.com/Microsoft/vscode/issues/12600

Node v6.6.0 (32-bit), Windows

Infobar:
`Cannot connect to runtime process, timeout after 10000 ms - (reason: Cannot connect to the target: 404 - Not Found. The requested location could not be found.).`

From command line: 
```
C:\src\node-interactive\hello-world>node --inspect --debug-brk app.js
Debugger listening on port 9229.
Warning: This is an experimental feature and could change at any time.
To start debugging, open the following URL in Chrome:
    chrome-devtools://devtools/remote/serve_file/@60cd6e859b9f557d2312f5bf532f6aec5f284980/inspector.html?experiments=true&v8only=true&ws=localhost:9229/node
C:\Program Files\nodejs\node.exe: src\inspector_socket.cc:553: Assertion `(inspector->http_parsing_state) == (nullptr)' failed.
```

Verbose logs: [vscode-node-debug2.txt](https://github.com/Microsoft/vscode-node-debug2/files/496666/vscode-node-debug2.txt)

**Comment by roblourens** [comment]
Just that windows crash :(
https://github.com/nodejs/node/issues/8155
