### ISSUE TITLE
Occasional set breakpoints request timeout issue during attach to process

### ISSUE THREAD

**Issue by mousetraps** [Microsoft/vscode-node-debug2#39]
Testing https://github.com/Microsoft/vscode/issues/12600

Node v6.6.0 (32-bit), Windows

No infobar, only a message printed to the debug console

![image](https://cloud.githubusercontent.com/assets/762848/18893216/c842b746-84c1-11e6-87f3-5f05a0e4709d.png)

![image](https://cloud.githubusercontent.com/assets/762848/18893179/93bee4cc-84c1-11e6-999d-ecf40450e1df.png)

Verbose logs:
[vscode-node-debug2.txt](https://github.com/Microsoft/vscode-node-debug2/files/496721/vscode-node-debug2.txt)

**Comment by roblourens** [comment]
The log shows that we never got a response from Chrome for one of the 3 breakpoints, and I have no idea why that happened, but I increased the timeout and fixed the other bug that prevented those BPs from binding in the first place
