### ISSUE TITLE
VSCode automatically saves file while debugging using nodemon

### ISSUE THREAD

**Issue by mousetraps** [Microsoft/vscode-node-debug2#49]
Testing Microsoft/vscode#14341

Launch config:

``` json
    {
            "name": "Attach nodemon",
            "type": "node",
            "request": "attach",
            "port": 9229,
            "verboseDiagnosticLogging": true,
            "restart": true
        }
```

In cmd prompt, run: `nodemon --debug-brk --inspect server.js`, and then attach vscode devbugger

Try editing `server.js` while app is running. Even though autosave is off, the editor will automatically save the file, which triggers a nodemon restart, debugger reattach, and makes it virtually impossible to edit the code in any substantive way.

**Comment by roblourens** [comment]
This one I just can't repro... pretty sure it's impossible for the debug adapter to impact this though.
