### ISSUE TITLE
Can't stop debugger after restarting while nodemon attached.

### ISSUE THREAD

**Issue by mousetraps** [Microsoft/vscode-node-debug2#50]
Testing Microsoft/vscode#14341

```json
        {
            "name": "Attach nodemon",
            "type": "node2",
            "request": "attach",
            "port": 9229,
            "verboseDiagnosticLogging": true,
            "restart": true
        }
```

1. in cmd, run `nodemon --debug-brk --inspect server.js`
2. attach debugger
3. restart debugger once it's attached

Attempting to stop the debugger fails, even when you Ctrl+C in the cmd line

**Comment by mousetraps** [comment]
Also a video of the incredibly weird state vscode ends up with by the end of it. 
[2016-10-25_14-31-09.zip](https://github.com/Microsoft/vscode-node-debug2/files/551852/2016-10-25_14-31-09.zip)

**Comment by roblourens** [comment]
Fixed - https://github.com/Microsoft/vscode-chrome-debug-core/commit/727f1e6413869bfa5c5427cde556d18b231c9c50
