### ISSUE TITLE
Support ProcessId option

### ISSUE THREAD

**Issue by mousetraps** [Microsoft/vscode-node-debug2#51]
Testing Microsoft/vscode#14341

#40 removed processId, but we should consider adding support for the option in order to maintain parity with the existing Node debugger

**Comment by roblourens** [comment]
The problem is that the existing debugger can put a process into debug mode dynamically if it wasn't launched in debug mode. You can't do that with --inspect yet, but there's a bug on Node for it. That makes processId not useful - you need to provide the port.
