### ISSUE TITLE
Support for time travel debugging

### ISSUE THREAD

**Issue by mousetraps** [Microsoft/vscode-node-debug2#52]
Testing Microsoft/vscode#14341

https://aka.ms/NodeTTD - when we go live with the node-debug2 debugger, we should probably ensure we have support for NodeChakra debugging as well. This would entail either ensuring that the --inspect flag is supported in NodeChakra, or that we have some way to fall back to the legacy debug engine.

**Comment by roblourens** [comment]
They are working on implementing --inspect. Not sure where it's at but we'll support it when they do.

**Comment by auchenberg** [comment]
Ping @joshgav

**Comment by auchenberg** [comment]
To me knowledge TTD hasn't been prototyped/built for CDP yet, but is on the roadmap.

**Comment by joshgav** [comment]
ChakraCore doesn't yet support the `--inspect` protocol ("Chrome Debugging Protocol") or the `type: node2` VS Code debugger type.

I think a good option would be to update the [TTD Readme](https://github.com/nodejs/node-chakracore/blob/debugging-ttd-preview/README.md#debug-a-ttd-trace-with-vscode) to explicitly state that `type: node` must be specified in the .vscode files to use TTD.

@aruneshchandra what do you think?

**Comment by aruneshchandra** [comment]
Yes CDP support is on the roadmap for Node-ChakraCore.  We can update the readme explicitly about the current support as well. When is CDP support going live in VSCode ?

**Comment by roblourens** [comment]
It's been there for a month, although we're still calling it 'experimental'.

**Comment by roblourens** [comment]
Hey @aruneshchandra, just curious, how is CDP work going in node-chakracore?

**Comment by aruneshchandra** [comment]
We are working on this right now. We are planning to introduce TTD as a separate domain in the schema. This will help in TTD feature detection and also allow a way to consolidate all the TTD based post-mortem (offline) debugging functionalities in its own schema. 

/cc: @kfarnung

**Comment by kfarnung** [comment]
Hey @roblourens, the CDP work is out for PR, I'm just wrapping up some final issues.  How is the TTD support coming from your side?  I'm hoping to get that all wired up this week and get a PR out.

**Comment by roblourens** [comment]
Will have that out ASAP. You're returning a domain named "TimeTravel", right?

**Comment by kfarnung** [comment]
@roblourens That's correct.  I'm working on landing the initial inspector changes this week and will start on that implementation ASAP.
