### ISSUE TITLE
Variables window doesn't update until next step after setting variable in debug console

### ISSUE THREAD

**Issue by mousetraps** [Microsoft/vscode-node-debug2#54]
Testing Microsoft/vscode#14341

```js
var screenName = "hello" 
console.log(screenName); // <- set breakpoint here
```

After setting a breakpoint on the second line, open the debug console, and type `screenName = "hiya"`. It is expected that the variables window updates to reflect this change, but it does not update until the next debug step.

**Comment by roblourens** [comment]
Yeah that's just vscode. I think it would be noisy to refresh all the variables after evaluating something in the console.
