### ISSUE TITLE
Consider linking to this github repo to make it easier for ppl to learn about / file issues

### ISSUE THREAD

**Issue by mousetraps** [Microsoft/vscode-node-debug2#55]
Testing Microsoft/vscode#14341

After this header text in the debug console, it might be helpful to add something like "Running into issues? Report them at https://github.com/Microsoft/vscode-node-debug2/issues", to increase engagement 
![image](https://cloud.githubusercontent.com/assets/762848/19705873/d66b40a0-9ac3-11e6-8ec5-05b4cf6a6c00.png)

**Comment by roblourens** [comment]
Those messages come from Node, and I'd thought about inserting something, but I don't know... plus I'm fine with people reporting issues at Microsoft/vscode.

**Comment by roblourens** [comment]
Docs have ended up on the official doc site.
