### ISSUE TITLE
Cannot set breakpoints for remote files

### ISSUE THREAD

**Issue by joshgav** [Microsoft/vscode-node-debug2#61]
Repro:

1. Cloned same git repo on remote host (Debian Stretch) and local host (macos 10.12).
2. Started Node process with `--inspect` on remote host.
3. Tunneled port 9229 over SSH to local Mac.
4. Opened local project on Mac with default launch.json config.
5. Successfully attached to remote process - process reported "Debugger attached".
6. Set a breakpoint in local VS Code files.
7. Took action in program which should've triggered the breakpoint but it didn't. Same scenario in Chrome DevTools v55 works.

For Chrome DevTools, websocket req/res is:

```
{"id":11,"method":"Debugger.setBreakpointByUrl","params":{"lineNumber":7,"url":"/home/joshgav/node/scratch/index.js","columnNumber":0,"condition":""}}
{"id":11,"result":{"breakpointId":"/home/joshgav/node/scratch/index.js:7:0","locations":[{"scriptId":"54","lineNumber":7,"columnNumber":2}]}}
```

and when breakpoint is hit this event is sent:

```
{"id":17,"result":{"breakpointId":"/home/joshgav/node/scratch/index.js:7:0","locations":[{"scriptId":"54","lineNumber":7,"columnNumber":2}]}}
```

For VS Code, websocket req/res is:
```
{"id":8,"method":"Debugger.setBreakpointByUrl","params":{"urlRegex":"\\/Users\\/joshgav\\/node\\/node-scratch\\/index\\.js","lineNumber":7,"columnNumber":0}}
{"id":8,"result":{"breakpointId":"/\\/Users\\/joshgav\\/node\\/node-scratch\\/index\\.js/:7:0","locations":[]}}
```

and the breakpoint is never hit.

Perhaps we should determine the URLs or IDs for files from information in `Debugger.scriptParsed` events. For example, here's one sent to Chrome DevTools:

```
{"method":"Debugger.scriptParsed","params":{"scriptId":"54","url":"/home/joshgav/node/scratch/index.js","startLine":0,"startColumn":0,"endLine":22,"endColumn":3,"executionConte
xtId":1,"hash":"D4EF4B80B651DC285DDEA6571BB62EC5F12
...
```

Somewhat relatedly, is there a way to attach and debug without a local project like CDT?

**Comment by roblourens** [comment]
Did you set localRoot/remoteRoot? That's what does the mapping of paths.

>Somewhat relatedly, is there a way to attach and debug without a local project like CDT?

No, that's a difference between our two models, we assume you're debugging from your workspace and have all the files locally available.

**Comment by joshgav** [comment]
Yes, that did it! Thank you!

For posterity, my launch.json file now looks like this:

```javascript
{
  "version": "0.2.0",
  "configurations": [
    {
      "name": "Launch Program",
      "type": "node2",
      "request": "launch",
      "program": "${workspaceRoot}/index.js",
      "cwd": "${workspaceRoot}"
    },
    {
      "name": "Attach to Process",
      "type": "node2",
      "request": "attach",
      "port": 9229,
      "localRoot": "/Users/joshgav/node/node-scratch",
      "remoteRoot": "/home/joshgav/node/scratch"
    }
  ]
}
```
