### ISSUE TITLE
non-existent method called when connecting

### ISSUE THREAD

**Issue by joshgav** [Microsoft/vscode-node-debug2#62]
FYI, you seem to be invoking a non-existent method when you connect, my network capture shows this each time:

```
{"id":5,"method":"Runtime.run"}
{"error":{"code":-32601,"message":"'Runtime.run' wasn't found"},"id":5}
```

**Comment by roblourens** [comment]
That's correct, I have to send multiple versions of that message because it changed across node versions.

**Comment by joshgav** [comment]
@roblourens thanks!
