### ISSUE TITLE
Run mode not working (noDebug option not correctly respected)

### ISSUE THREAD

**Issue by memotive** [Microsoft/vscode-node-debug2#69]
launch.json:
```
{
  "version": "0.2.0",
  "configurations": [
    {
      "type": "node2",
      "request": "launch",
      "name": "Launch 2",
      "program": "${workspaceRoot}/test.js",
      "cwd": "${workspaceRoot}"
    }
  ]
}
```
test.js:
```
var msg = "Hello World !";
console.log(msg);
```

Debug console in Run Mode:
```
node --debug-brk test.js 
Debugger listening on 127.0.0.1:5858
```
instead of

```
node --nolazy test.js 
Hello World !
```

**Comment by roblourens** [comment]
I don't understand the problem. You don't see the output of the console.log statement? Also your launch config says 'node2' but node2 would have launched with the --inspect flag, which isn't showing up in your log, and only 'node' would default to port 5858.

**Comment by memotive** [comment]
To compare old and new run modes, I have created 2 debug environments in launch.json:

1. 'Launch' with the standard Node Debug
2. 'Launch 2' with the experimental Node Debug 2

```
{
  "version": "0.2.0",
  "configurations": [
    {
      "type": "node",
      "request": "launch",
      "name": "Launch",
      "program": "${workspaceRoot}/test.js",
      "cwd": "${workspaceRoot}"
    },
    {
      "type": "node2",
      "request": "launch",
      "name": "Launch 2",
      "program": "${workspaceRoot}/test.js",
      "cwd": "${workspaceRoot}"
    }
  ]
}
```

Debug console in Run Mode (cmd+F5) with 'Launch' debug environment:
```
node --nolazy test.js 
Hello World !
```

Debug console in Run Mode (cmd+F5) with 'Launch 2' debug environment:
```
node --debug-brk test.js 
Debugger listening on 127.0.0.1:5858
```

Thanks for your support,
Pierre

**Comment by roblourens** [comment]
Oh, I understand the issue, thanks for the report.

**Comment by pierredewilde** [comment]
I have reported this issue using my company account (memotive) instead of my normal account (pierredewilde), but there are both equivalent.

The issue `#17304` is specific for `vscode 1.8` while the current issue is for `vscode 1.7`.

Notice that with `vscode 1.8`, there is an error but with `vscode 1.7,` nothing is displayed.

**Comment by roblourens** [comment]
This will be fixed in the next build of Insiders (next Monday)
