### ISSUE TITLE
Cannot attach to node2 debugger when using node running in WLS

### ISSUE THREAD

**Issue by nickolasclarke** [Microsoft/vscode-node-debug2#73]
- VSCode Version: v1..8.1
- OS Version: Win10 Pro 1607, 14393.576

Steps to Reproduce:

1. from WLS run ```  node --inspect=9229 --debug-brk ```
2. from VSCode run  `Attach to Port` profile, added from the `add configuration` floating-click-widget
3. Fails without error message, even with `code --verbose`

Launch.json configuration:
```json
"configurations": [
        
        {
            "type": "node",
            "request": "attach",
            "name": "Attach to Port",
            "port": 9229
        }
]
```

Workaround: 
change `"type":"node"` to '"type":"node2"`
save and retry

This simply appears to be a typo in the configuration template.

**Comment by roblourens** [comment]
Oh, dumb typo. Thanks for the PR!

**Comment by roblourens** [comment]
Oh, dumb typo. Thanks for the PR!

**Comment by nickolasclarke** [comment]
Of course! thanks.
