### ISSUE TITLE
HTTP GET failed: Error: connect ECONNREFUSED 127.0.0.1:11317

### ISSUE THREAD

**Issue by quanru** [Microsoft/vscode-node-debug2#76]
Verbose logs are written to /var/folders/gx/bcrb5wxj3fqcvvnb4l1nkglh0000gn/T/vscode-node-debug2.txt
10:42:07 PM, 1/9/2017
OS: darwin x64
Adapter node: v6.5.0 x64
vscode-chrome-debug-core: 3.8.1
node-debug2: 1.8.6
  ›From client: initialize({"adapterID":"node2","pathFormat":"path","linesStartAt1":true,"columnsStartAt1":true,"supportsVariableType":true,"supportsVariablePaging":true,"supportsRunInTerminalRequest":true})
  ›To client: {"seq":0,"type":"response","request_seq":1,"command":"initialize","success":true,"body":{"exceptionBreakpointFilters":[{"label":"All Exceptions","filter":"all","default":false},{"label":"Uncaught Exceptions","filter":"uncaught","default":true}],"supportsConfigurationDoneRequest":true,"supportsSetVariable":true,"supportsConditionalBreakpoints":true,"supportsCompletionsRequest":true,"supportsHitConditionalBreakpoints":true}}
  ›From client: launch({"type":"node2","request":"launch","name":"启动程序","verboseDiagnosticLogging":true,"program":"/Users/tihu/wacai/routers_service/server/server.js","cwd":"/Users/tihu/wacai/routers_service","runtimeExecutable":"/Users/tihu/wacai/routers_service/node_modules/.bin/babel-node","env":{"NODE_ENV":"development"},"sourceMaps":true})
Launch: program '/Users/tihu/wacai/routers_service/server/server.js' seems to be the generated file
/Users/tihu/wacai/routers_service/node_modules/.bin/babel-node --inspect=11317 --debug-brk server/server.js 
Discovering targets via http://127.0.0.1:11317/json
HTTP GET failed: Error: connect ECONNREFUSED 127.0.0.1:11317
Debugger listening on port 9229.
Warning: This is an experimental feature and could change at any time.
Discovering targets via http://127.0.0.1:11317/json
HTTP GET failed: Error: connect ECONNREFUSED 127.0.0.1:11317
Discovering targets via http://127.0.0.1:11317/json
HTTP GET failed: Error: connect ECONNREFUSED 127.0.0.1:11317
Discovering targets via http://127.0.0.1:11317/json
HTTP GET failed: Error: connect ECONNREFUSED 127.0.0.1:11317
Discovering targets via http://127.0.0.1:11317/json
HTTP GET failed: Error: connect ECONNREFUSED 127.0.0.1:11317
Discovering targets via http://127.0.0.1:11317/json
HTTP GET failed: Error: connect ECONNREFUSED 127.0.0.1:11317
Discovering targets via http://127.0.0.1:11317/json
HTTP GET failed: Error: connect ECONNREFUSED 127.0.0.1:11317

repeat for several times

 ›To client: {"seq":0,"type":"response","request_seq":2,"command":"launch","success":false,"message":"Cannot connect to runtime process, timeout after 10000 ms - (reason: Cannot connect to the target: connect ECONNREFUSED 127.0.0.1:11317).","body":{"error":{"id":2010,"format":"Cannot connect to runtime process, timeout after {_timeout} ms - (reason: {_error}).","variables":{"_error":"Cannot connect to the target: connect ECONNREFUSED 127.0.0.1:11317","_timeout":"10000"}}}}
  ›From client: disconnect({"restart":false})
Killing process with id: 2167
Terminated: Got disconnect request
  ›To client: {"seq":0,"type":"event","event":"terminated"}
  ›To client: {"seq":0,"type":"response","request_seq":3,"command":"disconnect","success":true}
Target exited
Terminated: Target exited
Target closed
Terminated: Target closed

this is the launch.json
```js
{
    // Use IntelliSense to learn about possible Node.js debug attributes.
    // Hover to view descriptions of existing attributes.
    // For more information, visit: https://go.microsoft.com/fwlink/?linkid=830387
    "version": "0.2.0",
    "configurations": [
        {
            "type": "node2",
            "request": "launch",
            "name": "启动程序",
            "verboseDiagnosticLogging": true,
            "program": "${workspaceRoot}/server/server.js",
            "cwd": "${workspaceRoot}",
            "runtimeExecutable": "${workspaceRoot}/node_modules/.bin/babel-node",
            "env": {
                "NODE_ENV": "development"
            },
            "sourceMaps": true
        },
        {
            "type": "node",
            "request": "attach",
            "name": "附加到进程",
            "port": 5858
        }
    ]
}
```

but another project of mine has the same lanuch.json, and it works

**Comment by roblourens** [comment]
Can you run `/Users/tihu/wacai/routers_service/node_modules/.bin/babel-node --inspect=11317 --debug-brk server/server.js` in a terminal and show the output? Is the node version recent enough to use --inspect? Or maybe that port is in use?

**Comment by nantas** [comment]
Hi @roblourens 

I have the exact same problem, trying to debug an Electron program in its main process, here's the diagnostic log:

```
OS: darwin x64
Adapter node: v6.5.0 x64
vscode-chrome-debug-core: 3.12.8
node-debug2: 1.10.0
/Users/nantas/workspace/bin/electron/Electron.app/Contents/MacOS/Electron --inspect=9451 --debug-brk ./ --dev
Discovering targets via http://127.0.0.1:9451/json
HTTP GET failed: Error: connect ECONNREFUSED 127.0.0.1:9451
```

If I run the command `/Users/nantas/workspace/bin/electron/Electron.app/Contents/MacOS/Electron --inspect=9451 --debug-brk ./ --dev` in terminal it gives no output. I don't think the port is taken since it's different every time.

**Comment by auchenberg** [comment]
@nantas This is because Electron doesn't yet support ``--inspect` and the new Inspector Protocol. You would have to use the V8-based debugger. See https://github.com/electron/electron/issues/6634

Using our regular Node debugger should automatically detect this, and allow to connect: http://code.visualstudio.com/updates/v1_10#_node-debugging

**Comment by nantas** [comment]
Thanks for the info.

Unfortunately the regular Node debugger does not work if the node environment is about v6.3. That's why I came to the new debugger in the first place.

For now I'm using nvm to switch the node environment when I have to debug my Electron app.

**Comment by roblourens** [comment]
The `node` on your path shouldn't make a difference to Electron. I'm pretty sure it will use whatever version of Node is included in Electron.

If you have `"protocol": "auto"` in your launch config, then node-debug will try to guess which debug protocol to use. But I don't think that's the case for you.
