### ISSUE TITLE
No visibility for variables from higher scopes in evaluation 

### ISSUE THREAD

**Issue by Spown** [Microsoft/vscode-node-debug2#79]
Despite being visible in the inspector, when trying to evaluate, variables from the other closures are not accessible. In my case current closure is a promise callback but it shouldn't make a difference anyway.

![](https://dl.dropboxusercontent.com/u/105338698/ShareX/2017-01/2017-01-19_21-38-08.png)

**Comment by roblourens** [comment]
Yeah, I see the same in Chrome devtools for variables that aren't referenced in the current scope. If I add a reference to it, then I can access it in the console. I think this is an unfortunate optimization from Chrome, nothing I can do about it.

**Comment by auchenberg** [comment]
Interesting, so Chrome makes references to watched properties in the console? We should aim to support this too.

**Comment by roblourens** [comment]
No, Chrome is doing the same thing here. I mean, if I add a reference in that scope in the script I'm debugging.

**Comment by auchenberg** [comment]
Ahhh :)

**Comment by Spown** [comment]
Maybe you could employ a dirty hack in a form of instrumental assignation of ref  to the variables of the same name in the current closure from the upper closures? I mean the missing variables are visible in the inspector so there is at least at some point a way to reach them. I don't know whether the VSC API or Chrome devtools could allow it, but maybe? And then maybe make them invisible in the current closure in the inspector. I imagine this would potentially create more problems, so maybe make it an config option, turned off by default.

Currently the evaluation feature of node2-debug is virtually useless, because limited by the current scope you basically only can call for a variable to inspect it and this is normally done through the inspector anyway. If you want to actually test some functionality you almost always have to get something (like a method to run a var through or another var to check against) from another scope.

I moved to node2-debug from node-debug, because [I was told](https://github.com/Microsoft/vscode-node-debug/issues/116#issuecomment-270335656) the unbearable problems it had couldn't be resolved and now  I'm in a exact same situation, only there is no node3-debug to move to...

**Comment by roblourens** [comment]
How can I bring Q into the closure if I can't access Q? I can't rewrite your code. A babel plugin could. You should file a bug on V8. It would be great if they didn't do this optimization with debug mode enabled.

**Comment by Spown** [comment]
> How can I bring Q into the closure if I can't access Q?

and how does Q appear in the inspector panel?

**Comment by roblourens** [comment]
It comes in a list from Chrome, but I can't eval some code to say `_q = <Q from other closure>`, and I won't get into the business of parsing the javascript in evals to look for Q. So if you have another idea, I'll gladly take a PR.

**Comment by roblourens** [comment]
I guess there's already an old V8 bug for this - https://bugs.chromium.org/p/v8/issues/detail?id=3491
and SO question with a good explanation - http://stackoverflow.com/questions/28388530/why-does-chrome-debugger-think-closed-local-variable-is-undefined

Also I noticed that only functions show up in the scope in this case - nothing else, which would limit the usefulness of any workaround.

**Comment by Spown** [comment]
yeah, I've seen these threads. I have no doubt that relying on the engines alone wouldn't help. I thought that if the inspector could reach other closures - eval could do the same. Apparently not. I don't know... If I did - I would submit a pull request already.

**Comment by Spown** [comment]
An Idea. Don't know how feasible it is, but still... When I'm unable to evaluate/get the value through the hover-over popup - I go to the Inspector panel and start opening closures an look for the variable manually. So maybe you could automate the same: instead of trying to bring in or access a var from another scope - just detect that the variable is unreachable and try to find an item/s in the Inspector's closure data stack starting from the closure directly above the current and untill there are none. If something is found - it can be output in the terminal/popup and just like there is this warning
![](https://drive.google.com/uc?id=0B-OJBofmehO3ZVV3N3pxaXdiTUU)
there could be a warning about the data not being a direct capture, but just an intelligent guess and that there is no warranty and such... Still better than nothing.

Thanks.
