### ISSUE TITLE
Get rid of (Experimental) in title - it is so out of fashion

### ISSUE THREAD

**Issue by isidorn** [Microsoft/vscode-node-debug2#80]
1. Experimental looks bad
2. Screws up the sorting
3. It is fine putting an experimental label somewhere but it does not have to be the first thing that pops up

![screen shot 2017-01-24 at 15 34 27](https://cloud.githubusercontent.com/assets/1926584/22251344/b72f7732-e24a-11e6-8059-4e5e0ac9aea7.png)

**Comment by joshgav** [comment]
FWIW Inspector (`node --inspect`) itself should come out of experimental some time in the Node 8.x timeframe (April-October), some discussion [here](https://github.com/nodejs/diagnostics/pull/80).

**Comment by roblourens** [comment]
Agreed that it looks weird and shouldn't be the first thing in the list. `"Node.js v6.3+ (Experimental): Launch"`?

**Comment by isidorn** [comment]
That is already better, though I leave the final touch up to you
