### ISSUE TITLE
Microsoft/vscode # 17902

### ISSUE THREAD

**Issue by jepiqueau** [Microsoft/vscode-node-debug2#84]
Error processing "evaluate": TypeError: Cannot read property 'Runtime' of undefined
    at CordovaDebugAdapter.globalEvaluate (C:\Users\Jean-Pierre\.vscode\extensions\vsmobile.cordova-tools-1.2.6\node_modules\vscode-chrome-debug-core\out\src\chrome\chromeDebugAdapter.js:1021:27)

the error is again there after i load the new vscode update

Version 1.9.0
date 2017-02-02
Interpreteur de commande 1.4.6
Convertisseur 53.0.785.143
Node 6.5.0

Can you please send me the modifications to be done in the javascript file as the typescript files are not available
src/chrome/chromeDebugAdapter
src/chrome/chromeConnection
src/error

I have a tendancy to update vscode each time i got a notification for a new update but i am wondering if it is a good practice

**Comment by roblourens** [comment]
It looks like you're using the Cordova debug adapter, can you open an issue on their repo? https://github.com/Microsoft/vscode-cordova

You may be using a watch which can cause an error like that at startup - if that's the problem, it should be fixed when they take the latest vscode-chrome-debug-core.
