### ISSUE TITLE
remove "Experimental Launch Configuration" snippet

### ISSUE THREAD

**Issue by weinand** [Microsoft/vscode-node-debug2#87]
remove "Experimental Launch Configuration" snippet because that scenario is covered by the identical "Launch Program" snippet of node-debug:

![2017-02-15_11-52-47](https://cloud.githubusercontent.com/assets/1898161/22971268/6bb817a0-f375-11e6-8eed-344b027ddb1d.png)

**Comment by roblourens** [comment]
Already done (just hadn't published yet)
