### ISSUE TITLE
Fix "Experimental Attach Configuration" snippet 

### ISSUE THREAD

**Issue by weinand** [Microsoft/vscode-node-debug2#88]
I'm not sure what to do with node2's "Experimental Attach Configuration" snippet.

Since it uses a different port number than node-debug's attach snippet, we can only remove it if we make node-debug's attach snippet 'smart' (e.g. by removing the `port` attribute from the snippet and setting the correct port in the extension code based on the protocol).

Alternatively we could keep the snippet but change its name to "Attach to Port 9229" (vs. "Attach to Port 5828"). Or "Attach to Inspect Port (9229)" vs. "Attach to Debug Port (5858)".

Let me know what approach you prefer.

**Comment by roblourens** [comment]
I think we should have two 'node' snippets, either named like "Attach to Port 9229", or like "Attach via Inspector Protocol" and "Attach via Legacy Protocol", with the port and protocol set.

**Comment by weinand** [comment]
@roblourens let's use the "Attach via Inspector Protocol" and "Attach via Legacy Protocol".

I've renamed my snippet to "Node.js: Attach via Legacy Protocol".
Let me know whether I should create a new snippet for "Attach via Inspector Protocol" on my side or whether you want to rename the existing one on your side.

**Comment by roblourens** [comment]
I added one to the node-debug repo to be consistent. Also added the protocol field.
