### ISSUE TITLE
Breakpoint at the last line

### ISSUE THREAD

**Issue by Spown** [Microsoft/vscode-node-debug2#90]
Setting a breakpoint on the last line while the adapter is running setts it on the next non-existant line and cant be removed.

![](https://dl.dropboxusercontent.com/u/105338698/ShareX/2017-02/2017-02-17_17-53-58.gif)

Setting the point while the debugger isn't running works ok, though.

**Comment by roblourens** [comment]
I pushed a fix for one case of this using sourcemaps, but I realized that there's another case without sourcemaps that can't really be fixed by the debug adapter. Filing an issue on vscode.
